swagger: '2.0'
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS access-paths os-replication-paths API
  contact: {}
  license:
    name: Commercial
basePath: /v1
tags:
- name: os-replication-paths
  description: 'OSReplicationPathController API /os-replication-paths.

    '
paths:
  /os-replication-paths/:
    get:
      tags:
      - os-replication-paths
      description: List os replication paths
      operationId: ListOSReplicationPaths
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        type: integer
        format: int64
        x-exportParamName: Limit
      - name: offset
        in: query
        description: paging param
        required: false
        type: integer
        format: int64
        x-exportParamName: Offset
      - name: marker
        in: query
        description: paging param
        required: false
        type: string
        x-exportParamName: Marker
      - name: replication_uuid
        in: query
        description: os replication uuid
        required: false
        type: string
        x-exportParamName: ReplicationUuid
      - name: allow_unknown_zone
        in: query
        description: allow has nil zone result(default true)
        required: false
        type: boolean
        x-exportParamName: AllowUnknownZone
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/OSReplicationPathsResp'
      security:
      - tokenInQuery: []
      - tokenInHeader: []
  /os-replication-paths/{path_uuid}:
    get:
      tags:
      - os-replication-paths
      description: Get a os replication path
      operationId: GetOSReplicationPath
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: path_uuid
        in: path
        description: replication path uuid
        required: true
        type: string
        x-exportParamName: PathUuid
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/OSReplicationPathResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
definitions:
  OSReplicationPathResp:
    type: object
    properties:
      os_replication_path:
        $ref: '#/definitions/OSReplicationPath'
    title: OSReplicationPathResp
    example:
      os_replication_path:
        replication_uuid: replication_uuid
        os_zone_uuids:
        - os_zone_uuids
        - os_zone_uuids
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        os_zones:
        - id: 7
          uuid: uuid
        - id: 7
          uuid: uuid
        uuid: uuid
        suspended: true
        status: status
  OSReplicationPath:
    type: object
    properties:
      create:
        type: string
        format: date-time
      os_zone_uuids:
        type: array
        items:
          type: string
      os_zones:
        type: array
        items:
          $ref: '#/definitions/ObjectStorageZone_Nestview'
      replication_uuid:
        type: string
      status:
        type: string
      suspended:
        type: boolean
      update:
        type: string
        format: date-time
      uuid:
        type: string
    title: OSReplicationPath
    description: OSReplicationPath defines models of os replication path.
    example:
      replication_uuid: replication_uuid
      os_zone_uuids:
      - os_zone_uuids
      - os_zone_uuids
      create: '2000-01-23T04:56:07.000+00:00'
      update: '2000-01-23T04:56:07.000+00:00'
      os_zones:
      - id: 7
        uuid: uuid
      - id: 7
        uuid: uuid
      uuid: uuid
      suspended: true
      status: status
  ObjectStorageZone_Nestview:
    type: object
    properties:
      id:
        type: integer
        format: int64
      uuid:
        type: string
    title: ObjectStorageZone_Nestview
    example:
      id: 7
      uuid: uuid
  OSReplicationPathsResp:
    type: object
    properties:
      os_replication_paths:
        type: array
        items:
          $ref: '#/definitions/OSReplicationPath'
    title: OSReplicationPathsResp
    example:
      os_replication_paths:
      - replication_uuid: replication_uuid
        os_zone_uuids:
        - os_zone_uuids
        - os_zone_uuids
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        os_zones:
        - id: 7
          uuid: uuid
        - id: 7
          uuid: uuid
        uuid: uuid
        suspended: true
        status: status
      - replication_uuid: replication_uuid
        os_zone_uuids:
        - os_zone_uuids
        - os_zone_uuids
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        os_zones:
        - id: 7
          uuid: uuid
        - id: 7
          uuid: uuid
        uuid: uuid
        suspended: true
        status: status
securityDefinitions:
  tokenInHeader:
    description: auth by token
    type: apiKey
    name: Xms-Auth-Token
    in: header
  tokenInQuery:
    description: auth by token
    type: apiKey
    name: token
    in: query
