openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Host Enc Specs API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: host-enc-specs
  description: HostEncSpecController API /host-enc-specs/
paths:
  /host-enc-specs/:
    get:
      tags:
      - host-enc-specs
      description: List host enclosure specs
      operationId: ListHostEncSpecs
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: model
        in: query
        description: host model
        required: false
        x-exportParamName: Model
        schema:
          type: string
      - name: vendor
        in: query
        description: host vendor
        required: false
        x-exportParamName: Vendor
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostEncSpecsResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List host enc specs
      x-summary-source: derived
    post:
      tags:
      - host-enc-specs
      description: Create a host enclosure spec
      operationId: CreateHostEncSpec
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostEncSpecResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HostEncSpecCreateReq'
        description: host enclosure spec info
        required: true
      summary: Create host enc spec
      x-summary-source: derived
  /host-enc-specs/{spec_id}:
    get:
      tags:
      - host-enc-specs
      description: Get host enclosure spec
      operationId: GetHostEncSpec
      parameters:
      - name: spec_id
        in: path
        description: host enclosure spec id
        required: true
        x-exportParamName: SpecId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostEncSpecResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get host enc spec
      x-summary-source: derived
    delete:
      tags:
      - host-enc-specs
      description: Delete a host enclosure spec
      operationId: DeleteHostEncSpec
      parameters:
      - name: spec_id
        in: path
        description: host enclosure spec id
        required: true
        x-exportParamName: SpecId
        schema:
          type: integer
          format: int64
      responses:
        204:
          description: No Content
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      summary: Delete host enc spec
      x-summary-source: derived
components:
  schemas:
    Enclosure:
      type: object
      properties:
        ids:
          type: array
          items:
            type: integer
            format: int64
        order:
          type: string
        position:
          type: string
        slot_num:
          type: integer
          format: int64
        start_slot:
          type: integer
          format: int64
      title: Enclosure
      description: Enclosure defines enclosure specification
      example:
        start_slot: 1
        slot_num: 6
        ids:
        - 0
        - 0
        position: position
        order: order
    HostEncSpecsResp:
      type: object
      required:
      - host_enc_specs
      properties:
        host_enc_specs:
          type: array
          description: host enclosure specs
          items:
            $ref: '#/components/schemas/HostEncSpec'
      title: HostEncSpecsResp
      example:
        host_enc_specs:
        - vendor: vendor
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          model: model
          id: 5
          enclosures:
          - start_slot: 1
            slot_num: 6
            ids:
            - 0
            - 0
            position: position
            order: order
          - start_slot: 1
            slot_num: 6
            ids:
            - 0
            - 0
            position: position
            order: order
        - vendor: vendor
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          model: model
          id: 5
          enclosures:
          - start_slot: 1
            slot_num: 6
            ids:
            - 0
            - 0
            position: position
            order: order
          - start_slot: 1
            slot_num: 6
            ids:
            - 0
            - 0
            position: position
            order: order
    HostEncSpecCreateReq_HostEncSpec:
      type: object
      required:
      - enclosures
      - model
      - vendor
      properties:
        enclosures:
          type: array
          description: host enclosures
          items:
            $ref: '#/components/schemas/Enclosure'
        model:
          type: string
          description: host model
        vendor:
          type: string
          description: host vendor
      title: HostEncSpecCreateReq_HostEncSpec
      example:
        vendor: vendor
        model: model
        enclosures:
        - start_slot: 1
          slot_num: 6
          ids:
          - 0
          - 0
          position: position
          order: order
        - start_slot: 1
          slot_num: 6
          ids:
          - 0
          - 0
          position: position
          order: order
    HostEncSpec:
      type: object
      properties:
        create:
          type: string
          format: date-time
        enclosures:
          type: array
          items:
            $ref: '#/components/schemas/Enclosure'
        id:
          type: integer
          format: int64
        model:
          type: string
        update:
          type: string
          format: date-time
        vendor:
          type: string
      title: HostEncSpec
      description: HostEncSpec defines host enclosure specification
      example:
        vendor: vendor
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        model: model
        id: 5
        enclosures:
        - start_slot: 1
          slot_num: 6
          ids:
          - 0
          - 0
          position: position
          order: order
        - start_slot: 1
          slot_num: 6
          ids:
          - 0
          - 0
          position: position
          order: order
    HostEncSpecResp:
      type: object
      required:
      - host_enc_spec
      properties:
        host_enc_spec:
          description: host enclosure spec
          $ref: '#/components/schemas/HostEncSpec'
      title: HostEncSpecResp
      example:
        host_enc_spec:
          vendor: vendor
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          model: model
          id: 5
          enclosures:
          - start_slot: 1
            slot_num: 6
            ids:
            - 0
            - 0
            position: position
            order: order
          - start_slot: 1
            slot_num: 6
            ids:
            - 0
            - 0
            position: position
            order: order
    HostEncSpecCreateReq:
      type: object
      properties:
        host_enc_spec:
          $ref: '#/components/schemas/HostEncSpecCreateReq_HostEncSpec'
      title: HostEncSpecCreateReq
      example:
        host_enc_spec:
          vendor: vendor
          model: model
          enclosures:
          - start_slot: 1
            slot_num: 6
            ids:
            - 0
            - 0
            position: position
            order: order
          - start_slot: 1
            slot_num: 6
            ids:
            - 0
            - 0
            position: position
            order: order
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
