openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Os Zone Locks API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: os-zone-locks
  description: OSZoneLockController API /os-zone-locks
paths:
  /os-zone-locks/:
    get:
      tags:
      - os-zone-locks
      description: List os zone locks.
      operationId: ListOSZoneLocks
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: all
        in: query
        description: show all zone locks
        required: false
        x-exportParamName: All
        schema:
          type: boolean
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSZoneLocksResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List OS zone locks
      x-summary-source: derived
    post:
      tags:
      - os-zone-locks
      description: Create a os zone lock.
      operationId: CreateOSZoneLock
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSZoneLockResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OSZoneLockCreateReq'
        description: os zone lock info
        required: true
      summary: Create OS zone lock
      x-summary-source: derived
  /os-zone-locks/{lock_uuid}:
    get:
      tags:
      - os-zone-locks
      description: Get a os zone lock.
      operationId: GetOSZoneLock
      parameters:
      - name: lock_uuid
        in: path
        description: os zone lock uuid
        required: true
        x-exportParamName: LockUuid
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSZoneLockResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get OS zone lock
      x-summary-source: derived
    delete:
      tags:
      - os-zone-locks
      description: Delete a os zone lock.
      operationId: DeleteOSZoneLock
      parameters:
      - name: lock_uuid
        in: path
        description: os zone lock uuid
        required: true
        x-exportParamName: LockUuid
        schema:
          type: string
      responses:
        204:
          description: No Content
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete OS zone lock
      x-summary-source: derived
  /os-zone-locks/{lock_uuid}:refresh:
    post:
      tags:
      - os-zone-locks
      description: Refresh a os zone lock.
      operationId: RefreshOSZoneLock
      parameters:
      - name: lock_uuid
        in: path
        description: os zone lock uuid
        required: true
        x-exportParamName: LockUuid
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSZoneLockResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Refresh OS zone lock
      x-summary-source: derived
components:
  schemas:
    OSZoneLocksResp:
      type: object
      required:
      - os_zone_locks
      properties:
        os_zone_locks:
          type: array
          items:
            $ref: '#/components/schemas/OSZoneLock'
      title: OSZoneLocksResp
      example:
        os_zone_locks:
        - resource_type: resource_type
          create: '2000-01-23T04:56:07.000+00:00'
          expired_time: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          uuid: uuid
          value: value
          key: key
        - resource_type: resource_type
          create: '2000-01-23T04:56:07.000+00:00'
          expired_time: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          uuid: uuid
          value: value
          key: key
    OSZoneLock:
      type: object
      properties:
        create:
          type: string
          format: date-time
        expired_time:
          type: string
          format: date-time
        key:
          type: string
        resource_type:
          type: string
        update:
          type: string
          format: date-time
        uuid:
          type: string
        value:
          type: string
      title: OSZoneLock
      description: OSZoneLock defines model of os zone lock.
      example:
        resource_type: resource_type
        create: '2000-01-23T04:56:07.000+00:00'
        expired_time: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        uuid: uuid
        value: value
        key: key
    OSZoneLockCreateReq:
      type: object
      properties:
        os_zone_lock:
          $ref: '#/components/schemas/OSZoneLockCreateReq_Lock'
      title: OSZoneLockCreateReq
    OSZoneLockResp:
      type: object
      required:
      - os_zone_lock
      properties:
        os_zone_lock:
          $ref: '#/components/schemas/OSZoneLock'
      title: OSZoneLockResp
      example:
        os_zone_lock:
          resource_type: resource_type
          create: '2000-01-23T04:56:07.000+00:00'
          expired_time: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          uuid: uuid
          value: value
          key: key
    OSZoneLockCreateReq_Lock:
      type: object
      required:
      - key
      - resource_type
      - value
      properties:
        key:
          type: string
          description: key of lock, for example name of os bucket
        resource_type:
          type: string
          description: resource type of lock, including os_bucket
        value:
          type: string
          description: value of lock, for example action of os bucket
      title: OSZoneLockCreateReq_Lock
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
