openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Protection Domains API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: Protection Domains
  description: ProtectionDomainController Protection Domain Management
paths:
  /protection-domains/:
    get:
      tags:
      - Protection Domains
      operationId: ListProtectionDomains
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProtectionDomainRecordsResp'
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List protection domains
      x-summary-source: derived
  /protection-domains/{protection_domain_id}:
    get:
      tags:
      - Protection Domains
      description: get protection domain
      operationId: GetProtectionDomain
      parameters:
      - name: protection_domain_id
        in: path
        description: protection domain id
        required: true
        x-exportParamName: ProtectionDomainId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProtectionDomainRecordResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get protection domain
      x-summary-source: derived
components:
  schemas:
    PdRecord:
      title: PdRecord
      allOf:
      - $ref: '#/components/schemas/ProtectionDomain'
      description: PdRecord defines the response content of protection domain related API
    ProtectionDomainRecordsResp:
      type: object
      required:
      - protection_domains
      properties:
        protection_domains:
          type: array
          description: protection domains
          items:
            $ref: '#/components/schemas/PdRecord'
      title: ProtectionDomainRecordsResp
      example:
        protection_domains:
        - ''
        - ''
    PlacementNodeProperties:
      type: object
      properties:
        is_witness:
          type: boolean
          description: whether this is a witness node
      title: PlacementNodeProperties
      description: PlacementNodeProperties contains properties for a placement node.
      example:
        is_witness: true
    ProtectionDomainRecordResp:
      type: object
      required:
      - protection_domain
      properties:
        protection_domain:
          description: protection domain
          $ref: '#/components/schemas/PdRecord'
      title: ProtectionDomainRecordResp
      example:
        protection_domain: ''
    PlacementNode_Nestview_parent:
      properties:
        create:
          type: string
          format: date-time
          description: time of creating placement node
        id:
          type: integer
          format: int64
          description: id of placement node
        name:
          type: string
          description: name of placement node
        parent:
          description: parent of placement node
          $ref: '#/components/schemas/PlacementNode'
        properties:
          description: properties for this placement node like is_witness
          $ref: '#/components/schemas/PlacementNodeProperties'
        type:
          type: string
          description: type of placement node
        update:
          type: string
          format: date-time
          description: time of updating placement node
      description: parent of placement node
    PlacementNode_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: id of placement node
        parent:
          $ref: '#/components/schemas/PlacementNode_Nestview_parent'
      title: PlacementNode_Nestview
    ProtectionDomain:
      type: object
      properties:
        create:
          type: string
          format: date-time
          description: time of creating protection domain
        description:
          type: string
          description: description of protection domain
        id:
          type: integer
          format: int64
          description: id of protection domain
        name:
          type: string
          description: name of protection domain
        placement_node:
          description: placement node of protection domain
          $ref: '#/components/schemas/PlacementNode_Nestview'
        status:
          type: string
          description: status protection domain
        update:
          type: string
          format: date-time
          description: time of updating protection domain
      title: ProtectionDomain
      description: ProtectionDomain defines protection domain objects
    PlacementNode:
      type: object
      properties:
        create:
          type: string
          format: date-time
          description: time of creating placement node
        id:
          type: integer
          format: int64
          description: id of placement node
        name:
          type: string
          description: name of placement node
        parent:
          description: parent of placement node
          $ref: '#/components/schemas/PlacementNode'
        properties:
          description: properties for this placement node like is_witness
          $ref: '#/components/schemas/PlacementNodeProperties'
        type:
          type: string
          description: type of placement node
        update:
          type: string
          format: date-time
          description: time of updating placement node
      title: PlacementNode
      description: PlacementNode defines a placement node managing a range of hosts
      example:
        parent: null
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        id: 6
        type: type
        properties:
          is_witness: true
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
