openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Identity Platforms API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: identity-platforms
  description: IdentityPlatformController Identity Platform Management
paths:
  /identity-platforms/:
    get:
      tags:
      - identity-platforms
      operationId: ListIdentityPlatforms
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentityPlatformsResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List identity platforms
      x-summary-source: derived
    post:
      tags:
      - identity-platforms
      operationId: CreateIdentityPlatform
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentityPlatformResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdentityPlatformCreateReq'
        description: identity platform info
        required: true
      summary: Create identity platform
      x-summary-source: derived
  /identity-platforms/{identity_platform_id}:
    get:
      tags:
      - identity-platforms
      description: Get a identity platform
      operationId: GetIdentityPlatform
      parameters:
      - name: identity_platform_id
        in: path
        description: identity platform id
        required: true
        x-exportParamName: IdentityPlatformId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentityPlatformResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get identity platform
      x-summary-source: derived
    delete:
      tags:
      - identity-platforms
      operationId: DeleteIdentityPlatform
      parameters:
      - name: identity_platform_id
        in: path
        description: identity platform id
        required: true
        x-exportParamName: IdentityPlatformId
        schema:
          type: integer
          format: int64
      responses:
        204:
          description: No Content
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete identity platform
      x-summary-source: derived
    patch:
      tags:
      - identity-platforms
      description: Update a identity platform
      operationId: UpdateIdentityPlatform
      parameters:
      - name: identity_platform_id
        in: path
        description: identity platform id
        required: true
        x-exportParamName: IdentityPlatformId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentityPlatformResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdentityPlatformUpdateReq'
        description: identity platform info
        required: true
      summary: Update identity platform
      x-summary-source: derived
  /identity-platforms/{identity_platform_id}:regenerate:
    post:
      tags:
      - identity-platforms
      description: regenereate a identity platform key
      operationId: RegenerateIdentityKey
      parameters:
      - name: identity_platform_id
        in: path
        description: identity platform id
        required: true
        x-exportParamName: IdentityPlatformId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentityPlatformResp'
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Regenerate identity key
      x-summary-source: derived
components:
  schemas:
    IdentityPlatformUpdateReq_Platform:
      type: object
      properties:
        enabled:
          type: boolean
        name:
          type: string
          description: name of identity platform
        url:
          type: string
      title: IdentityPlatformUpdateReq_Platform
      example:
        name: name
        enabled: true
        url: url
    IdentityPlatform:
      type: object
      properties:
        create:
          type: string
          format: date-time
          description: time of creating identity platform
        enabled:
          type: boolean
          description: enable the identity platform or not
        failure_num:
          type: integer
          format: int64
          description: num of failed authorization
        id:
          type: integer
          format: int64
          description: id of identity platform
        key:
          type: string
          description: secret key of identity platform
        name:
          type: string
          description: name of identity platform
        success_num:
          type: integer
          format: int64
          description: num of successful authorization
        type:
          type: string
          description: type of identity platform
        update:
          type: string
          format: date-time
          description: time of updating identity platform
        url:
          type: string
          description: url of identity platform
        uuid:
          type: string
      title: IdentityPlatform
      description: IdentityPlatform defines different platforms for auth
      example:
        failure_num: 0
        success_num: 1
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        id: 6
        type: type
        uuid: uuid
        enabled: true
        key: key
        url: url
    IdentityPlatformsResp:
      type: object
      properties:
        identity_platforms:
          type: array
          description: identity platforms
          items:
            $ref: '#/components/schemas/IdentityPlatform'
      title: IdentityPlatformsResp
      example:
        identity_platforms:
        - failure_num: 0
          success_num: 1
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 6
          type: type
          uuid: uuid
          enabled: true
          key: key
          url: url
        - failure_num: 0
          success_num: 1
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 6
          type: type
          uuid: uuid
          enabled: true
          key: key
          url: url
    IdentityPlatformCreateReq_Platform:
      type: object
      properties:
        enabled:
          type: boolean
        name:
          type: string
          description: name of identity platform
        type:
          type: string
          description: type of identity platform
        url:
          type: string
      title: IdentityPlatformCreateReq_Platform
      example:
        name: name
        type: type
        enabled: true
        url: url
    IdentityPlatformCreateReq:
      type: object
      properties:
        identity_platform:
          $ref: '#/components/schemas/IdentityPlatformCreateReq_Platform'
      title: IdentityPlatformCreateReq
      example:
        identity_platform:
          name: name
          type: type
          enabled: true
          url: url
    IdentityPlatformResp:
      type: object
      properties:
        identity_platform:
          description: identity platform
          $ref: '#/components/schemas/IdentityPlatform'
      title: IdentityPlatformResp
      example:
        identity_platform:
          failure_num: 0
          success_num: 1
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 6
          type: type
          uuid: uuid
          enabled: true
          key: key
          url: url
    IdentityPlatformUpdateReq:
      type: object
      properties:
        identity_platform:
          $ref: '#/components/schemas/IdentityPlatformUpdateReq_Platform'
      title: IdentityPlatformUpdateReq
      example:
        identity_platform:
          name: name
          enabled: true
          url: url
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
