openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Email Groups API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: email-groups
  description: EmailGroupController Operations about Email
paths:
  /email-groups/:
    get:
      tags:
      - email-groups
      description: List all email groups
      operationId: ListEmailGroups
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: alert_group_id
        in: query
        description: alert group id
        required: false
        x-exportParamName: AlertGroupId
        schema:
          type: integer
          format: int64
      - name: name
        in: query
        description: name of email groups
        required: false
        x-exportParamName: Name
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailGroupsResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List email groups
      x-summary-source: derived
    post:
      tags:
      - email-groups
      description: create email group
      operationId: CreateEmailGroup
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailGroupResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailGroupUpdateReq'
        description: email group
        required: true
      summary: Create email group
      x-summary-source: derived
  /email-groups/{group_id}:
    get:
      tags:
      - email-groups
      description: get email group
      operationId: GetEmailGroup
      parameters:
      - name: group_id
        in: path
        description: the id of email group
        required: true
        x-exportParamName: GroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailGroupResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get email group
      x-summary-source: derived
    put:
      tags:
      - email-groups
      description: update email group
      operationId: UpdateEmailGroup
      parameters:
      - name: group_id
        in: path
        description: the id of email group
        required: true
        x-exportParamName: GroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailGroupResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailGroupUpdateReq'
        description: email group
        required: true
      summary: Update email group
      x-summary-source: derived
    delete:
      tags:
      - email-groups
      description: delete email group
      operationId: DeleteEmailGroup
      parameters:
      - name: group_id
        in: path
        description: the id of email group
        required: true
        x-exportParamName: GroupId
        schema:
          type: integer
          format: int64
      responses:
        204:
          description: No Content
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete email group
      x-summary-source: derived
components:
  schemas:
    EmailGroupsResp:
      type: object
      required:
      - email_groups
      properties:
        email_groups:
          type: array
          description: email groups
          items:
            $ref: '#/components/schemas/EmailGroupRecord'
      title: EmailGroupsResp
      example:
        email_groups:
        - ''
        - ''
    EmailGroup:
      type: object
      properties:
        create:
          type: string
          format: date-time
        emails:
          type: array
          items:
            type: string
        id:
          type: integer
          format: int64
        name:
          type: string
        update:
          type: string
          format: date-time
      title: EmailGroup
      description: EmailGroup defines the email group
    EmailGroupUpdateReq_EmailGroup:
      type: object
      required:
      - emails
      - name
      properties:
        emails:
          type: array
          items:
            type: string
        name:
          type: string
      title: EmailGroupUpdateReq_EmailGroup
      example:
        emails:
        - emails
        - emails
        name: name
    EmailGroupUpdateReq:
      type: object
      required:
      - email_group
      properties:
        email_group:
          $ref: '#/components/schemas/EmailGroupUpdateReq_EmailGroup'
      title: EmailGroupUpdateReq
      example:
        email_group:
          emails:
          - emails
          - emails
          name: name
    EmailGroupRecord:
      title: EmailGroupRecord
      allOf:
      - $ref: '#/components/schemas/EmailGroup'
      description: EmailGroupRecord defines email group record
    EmailGroupResp:
      type: object
      required:
      - email_group
      properties:
        email_group:
          description: email group
          $ref: '#/components/schemas/EmailGroupRecord'
      title: EmailGroupResp
      example:
        email_group: ''
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
