openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Fs Nfs Shares API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: fs-nfs-shares
  description: FSNFSShareController provides API for fs nfs shares
paths:
  /fs-nfs-shares/:
    get:
      tags:
      - fs-nfs-shares
      description: List fs nfs sharess
      operationId: ListFSNFSShares
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: fs_folder_id
        in: query
        description: fs nfs id
        required: false
        x-exportParamName: FsFolderId
        schema:
          type: integer
          format: int64
      - name: fs_gateway_group_id
        in: query
        description: file storage gateway group id
        required: false
        x-exportParamName: FsGatewayGroupId
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSNFSSharesResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List FSNFS shares
      x-summary-source: derived
    post:
      tags:
      - fs-nfs-shares
      description: Create fs nfs shares
      operationId: CreateFSNFSShare
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSNFSShareResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSNFSShareCreateReq'
        description: share info
        required: true
      summary: Create FSNFS share
      x-summary-source: derived
  /fs-nfs-shares/{fs_nfs_share_id}:
    get:
      tags:
      - fs-nfs-shares
      description: Get fs nfs shares
      operationId: GetFSNFSShare
      parameters:
      - name: fs_nfs_share_id
        in: path
        description: share id
        required: true
        x-exportParamName: FsNfsShareId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSNFSShareResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get FSNFS share
      x-summary-source: derived
    delete:
      tags:
      - fs-nfs-shares
      description: delete fs nfs shares
      operationId: DeleteFSNFSShare
      parameters:
      - name: fs_nfs_share_id
        in: path
        description: share id
        required: true
        x-exportParamName: FsNfsShareId
        schema:
          type: integer
          format: int64
      - name: force
        in: query
        description: force delete or not
        required: false
        x-exportParamName: Force
        schema:
          type: boolean
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSNFSShareResp'
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      summary: Delete FSNFS share
      x-summary-source: derived
  /fs-nfs-shares/{fs_nfs_share_id}:add-acls:
    post:
      tags:
      - fs-nfs-shares
      description: Add fs nfs shares acls
      operationId: AddFSNFSShareACLs
      parameters:
      - name: fs_nfs_share_id
        in: path
        description: fs nfs shares id
        required: true
        x-exportParamName: FsNfsShareId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSNFSShareResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSNFSShareAddACLsReq'
        description: share acls info
        required: true
      summary: Add FSNFS share ACLs
      x-summary-source: derived
  /fs-nfs-shares/{fs_nfs_share_id}:remove-acls:
    post:
      tags:
      - fs-nfs-shares
      description: remove fs nfs shares acls
      operationId: RemoveFSNFSShareACLs
      parameters:
      - name: fs_nfs_share_id
        in: path
        description: fs nfs shares id
        required: true
        x-exportParamName: FsNfsShareId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSNFSShareResp'
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSNFSShareRemoveACLsReq'
        description: share acls info
        required: true
      summary: Remove FSNFS share ACLs
      x-summary-source: derived
  /fs-nfs-shares/{fs_nfs_share_id}:update-acls:
    post:
      tags:
      - fs-nfs-shares
      description: Update fs nfs share acls
      operationId: UpdateFSNFSShareACLs
      parameters:
      - name: fs_nfs_share_id
        in: path
        description: share id
        required: true
        x-exportParamName: FsNfsShareId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSNFSShareResp'
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSNFSShareResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSNFSShareUpdateACLsReq'
        description: share info
        required: true
      summary: Update FSNFS share ACLs
      x-summary-source: derived
components:
  schemas:
    FSGatewayGroup_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        vip:
          type: string
        vip_mask:
          type: integer
          format: int64
      title: FSGatewayGroup_Nestview
      example:
        name: name
        id: 6
        vip_mask: 1
        vip: vip
    FSNFSShareCreateReq:
      type: object
      required:
      - fs_nfs_share
      properties:
        fs_nfs_share:
          $ref: '#/components/schemas/FSNFSShareCreateReq_Share'
      title: FSNFSShareCreateReq
    FSNFSShare:
      type: object
      properties:
        acl_num:
          type: integer
          format: int64
        action_status:
          type: string
        create:
          type: string
          format: date-time
        fs_folder:
          $ref: '#/components/schemas/FSFolder_Nestview'
        fs_gateway_group:
          $ref: '#/components/schemas/FSGatewayGroup_Nestview'
        fs_quota_tree:
          $ref: '#/components/schemas/FSQuotaTree_Nestview'
        id:
          type: integer
          format: int64
        mapping_num:
          type: integer
          format: int64
        status:
          type: string
        update:
          type: string
          format: date-time
      title: FSNFSShare
      description: FSNFSShare defines model of fs nfs share
      example:
        mapping_num: 1
        fs_folder:
          name: name
          id: 6
        create: '2000-01-23T04:56:07.000+00:00'
        fs_quota_tree:
          name: name
          id: 5
        update: '2000-01-23T04:56:07.000+00:00'
        acl_num: 0
        id: 6
        fs_gateway_group:
          name: name
          id: 6
          vip_mask: 1
          vip: vip
        action_status: action_status
        status: status
    FSFolder_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: FSFolder_Nestview
      example:
        name: name
        id: 6
    FSNFSShareUpdateACLsReq_Share:
      type: object
      properties:
        fs_nfs_share_acls:
          type: array
          description: access control array
          items:
            $ref: '#/components/schemas/FSNFSShareUpdateACLReq'
      title: FSNFSShareUpdateACLsReq_Share
    FSNFSShareUpdateACLReq:
      type: object
      properties:
        all_squash:
          type: boolean
          description: all squash
        id:
          type: integer
          format: int64
          description: id of user group
        permission:
          type: string
          description: readonly or readwrite access
        root_squash:
          type: boolean
          description: root squash
        sync:
          type: boolean
          description: write to disk by sync or async
      title: FSNFSShareUpdateACLReq
    FSQuotaTree_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: FSQuotaTree_Nestview
      example:
        name: name
        id: 5
    FSNFSShareRemoveACLsReq:
      type: object
      required:
      - fs_nfs_share
      properties:
        fs_nfs_share:
          $ref: '#/components/schemas/FSNFSShareRemoveACLsReq_Share'
      title: FSNFSShareRemoveACLsReq
    FSNFSSharesResp:
      type: object
      required:
      - fs_nfs_shares
      properties:
        fs_nfs_shares:
          type: array
          description: share
          items:
            $ref: '#/components/schemas/FSNFSShare'
      title: FSNFSSharesResp
      example:
        fs_nfs_shares:
        - mapping_num: 1
          fs_folder:
            name: name
            id: 6
          create: '2000-01-23T04:56:07.000+00:00'
          fs_quota_tree:
            name: name
            id: 5
          update: '2000-01-23T04:56:07.000+00:00'
          acl_num: 0
          id: 6
          fs_gateway_group:
            name: name
            id: 6
            vip_mask: 1
            vip: vip
          action_status: action_status
          status: status
        - mapping_num: 1
          fs_folder:
            name: name
            id: 6
          create: '2000-01-23T04:56:07.000+00:00'
          fs_quota_tree:
            name: name
            id: 5
          update: '2000-01-23T04:56:07.000+00:00'
          acl_num: 0
          id: 6
          fs_gateway_group:
            name: name
            id: 6
            vip_mask: 1
            vip: vip
          action_status: action_status
          status: status
    FSNFSShareRemoveACLsReq_Share:
      type: object
      required:
      - fs_nfs_share_acl_ids
      properties:
        fs_nfs_share_acl_ids:
          type: array
          description: access control array
          items:
            type: integer
            format: int64
      title: FSNFSShareRemoveACLsReq_Share
    FSNFSShareUpdateACLsReq:
      type: object
      required:
      - fs_nfs_share
      properties:
        fs_nfs_share:
          $ref: '#/components/schemas/FSNFSShareUpdateACLsReq_Share'
      title: FSNFSShareUpdateACLsReq
    FSNFSShareAddACLsReq_Share:
      type: object
      required:
      - fs_nfs_share_acls
      properties:
        fs_nfs_share_acls:
          type: array
          description: access control array
          items:
            $ref: '#/components/schemas/FSNFSShareACLReq'
      title: FSNFSShareAddACLsReq_Share
    FSNFSShareResp:
      type: object
      required:
      - fs_nfs_share
      properties:
        fs_nfs_share:
          description: folder share
          $ref: '#/components/schemas/FSNFSShare'
      title: FSNFSShareResp
      example:
        fs_nfs_share:
          mapping_num: 1
          fs_folder:
            name: name
            id: 6
          create: '2000-01-23T04:56:07.000+00:00'
          fs_quota_tree:
            name: name
            id: 5
          update: '2000-01-23T04:56:07.000+00:00'
          acl_num: 0
          id: 6
          fs_gateway_group:
            name: name
            id: 6
            vip_mask: 1
            vip: vip
          action_status: action_status
          status: status
    FSNFSShareACLReq:
      type: object
      properties:
        all_squash:
          type: boolean
          description: all squash
        fs_client_group_id:
          type: integer
          format: int64
          description: id of cilent group
        fs_client_id:
          type: integer
          format: int64
          description: id of cilent
        id:
          type: integer
          format: int64
          description: id of user group
        permission:
          type: string
          description: readonly or readwrite access
        root_squash:
          type: boolean
          description: root squash
        sync:
          type: boolean
          description: write to disk by sync or async
        type:
          type: string
          description: type of share acl
      title: FSNFSShareACLReq
    FSNFSShareAddACLsReq:
      type: object
      required:
      - fs_nfs_share
      properties:
        fs_nfs_share:
          $ref: '#/components/schemas/FSNFSShareAddACLsReq_Share'
      title: FSNFSShareAddACLsReq
    FSNFSShareCreateReq_Share:
      type: object
      required:
      - fs_folder_id
      - fs_gateway_group_id
      properties:
        fs_folder_id:
          type: integer
          format: int64
          description: folder id
        fs_gateway_group_id:
          type: integer
          format: int64
          description: gateway group id
        fs_nfs_share_acls:
          type: array
          description: access control array
          items:
            $ref: '#/components/schemas/FSNFSShareACLReq'
        fs_quota_tree_id:
          type: integer
          format: int64
          description: quota tree id
      title: FSNFSShareCreateReq_Share
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
