openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Os Lifecycles API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: os-lifecycles
  description: ObjectStorageLifecycleController provides API for object storage lifecycle
paths:
  /os-lifecycles/:
    get:
      tags:
      - os-lifecycles
      description: List object storage lifecycles
      operationId: ListLifecycles
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectStorageLifecyclesResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List lifecycles
      x-summary-source: derived
  /os-lifecycles/{lifecycle_id}:
    get:
      tags:
      - os-lifecycles
      description: Get object storage lifecycle
      operationId: GetLifecycle
      parameters:
      - name: lifecycle_id
        in: path
        description: lifecycle id
        required: true
        x-exportParamName: LifecycleId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectStorageLifecycleResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get lifecycle
      x-summary-source: derived
components:
  schemas:
    ObjectStorageLifecycleResp:
      type: object
      required:
      - os_lifecycle
      properties:
        os_lifecycle:
          description: object storage lifecycle
          $ref: '#/components/schemas/ObjectStorageLifecycle'
      title: ObjectStorageLifecycleResp
      example:
        os_lifecycle:
          rules:
          - '{}'
          - '{}'
          id: 6
          status: status
    ObjectStorageLifecyclesResp:
      type: object
      required:
      - os_lifecycles
      properties:
        os_lifecycles:
          type: array
          description: object storage lifecycles
          items:
            $ref: '#/components/schemas/ObjectStorageLifecycle'
      title: ObjectStorageLifecyclesResp
      example:
        os_lifecycles:
        - rules:
          - '{}'
          - '{}'
          id: 6
          status: status
        - rules:
          - '{}'
          - '{}'
          id: 6
          status: status
    ObjectStorageLifecycle:
      type: object
      properties:
        id:
          type: integer
          format: int64
        rules:
          type: array
          items:
            type: object
            properties: {}
        status:
          type: string
      title: ObjectStorageLifecycle
      description: ObjectStorageLifecycle is the model of object_storage_lifecycle
      example:
        rules:
        - '{}'
        - '{}'
        id: 6
        status: status
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
