openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Domain User Validators API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: domain-user-validators
  description: DomainUserValidatorController Domain User Validator Management
paths:
  /domain-user-validators/:
    post:
      tags:
      - domain-user-validators
      operationId: CreateDomainUserValidator
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainUserValidatorResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DomainUserValidatorCreateReq'
        description: domain user validator info
        required: true
      summary: Create domain user validator
      x-summary-source: derived
  /domain-user-validators/{domain_user_validator_id}:
    get:
      tags:
      - domain-user-validators
      description: Get domain_user validator
      operationId: GetDomainUserValidator
      parameters:
      - name: domain_user_validator_id
        in: path
        description: domain user validator id
        required: true
        x-exportParamName: DomainUserValidatorId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainUserValidatorResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get domain user validator
      x-summary-source: derived
components:
  schemas:
    DomainUserValidatorCreateReq_Validator:
      type: object
      required:
      - type
      properties:
        groups:
          type: array
          description: Domain groups
          items:
            type: string
        type:
          type: string
          description: Domain type
        users:
          type: array
          description: Domain users
          items:
            type: string
      title: DomainUserValidatorCreateReq_Validator
      example:
        groups:
        - groups
        - groups
        type: type
        users:
        - users
        - users
    DomainUserValidatorCreateReq:
      type: object
      properties:
        domain_user_validator:
          $ref: '#/components/schemas/DomainUserValidatorCreateReq_Validator'
      title: DomainUserValidatorCreateReq
      example:
        domain_user_validator:
          groups:
          - groups
          - groups
          type: type
          users:
          - users
          - users
    DomainUserValidatorResp:
      type: object
      properties:
        domain_user_validator:
          $ref: '#/components/schemas/DomainUserValidator'
      title: DomainUserValidatorResp
      example:
        domain_user_validator:
          members: '{}'
          report: '{}'
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 0
          type: type
          status: status
    DomainUserValidator:
      type: object
      properties:
        create:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        members:
          type: object
          properties: {}
        report:
          type: object
          properties: {}
        status:
          type: string
        type:
          type: string
        update:
          type: string
          format: date-time
      title: DomainUserValidator
      description: DomainUserValidator defines the validator for domain users
      example:
        members: '{}'
        report: '{}'
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        id: 0
        type: type
        status: status
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
