swagger: '2.0'
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS access-paths network-addresses API
  contact: {}
  license:
    name: Commercial
basePath: /v1
tags:
- name: network-addresses
  description: 'NetworkAddressController Network Address Management

    '
paths:
  /network-addresses/:
    get:
      tags:
      - network-addresses
      description: List network addresses
      operationId: ListNetworkAddresses
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        type: integer
        format: int64
        x-exportParamName: Limit
      - name: offset
        in: query
        description: paging param
        required: false
        type: integer
        format: int64
        x-exportParamName: Offset
      - name: network_interface_id
        in: query
        description: network interface id
        required: false
        type: integer
        format: int64
        x-exportParamName: NetworkInterfaceId
      - name: host_id
        in: query
        description: host id
        required: false
        type: integer
        format: int64
        x-exportParamName: HostId
      - name: role
        in: query
        description: network address role
        required: false
        type: string
        x-exportParamName: Role
      - name: vip_group_id
        in: query
        description: vip group id
        required: false
        type: integer
        format: int64
        x-exportParamName: VipGroupId
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/NetworkAddressesResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
  /network-addresses/{network_address_id}:
    get:
      tags:
      - network-addresses
      description: Get a network address
      operationId: GetNetworkAddress
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: network_address_id
        in: path
        description: network address id
        required: true
        type: integer
        format: int64
        x-exportParamName: NetworkAddressId
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/NetworkAddressResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
definitions:
  NetworkInterface_Nestview:
    type: object
    properties:
      id:
        type: integer
        format: int64
      mac_address:
        type: string
      name:
        type: string
    title: NetworkInterface_Nestview
    example:
      mac_address: mac_address
      name: name
      id: 1
  Host_Nestview:
    type: object
    required:
    - admin_ip
    properties:
      admin_ip:
        type: string
      id:
        type: integer
        format: int64
      name:
        type: string
    title: Host_Nestview
    example:
      name: name
      admin_ip: admin_ip
      id: 0
  NetworkAddressesResp:
    type: object
    properties:
      network_addresses:
        type: array
        description: network address records
        items:
          $ref: '#/definitions/NetworkAddress'
    title: NetworkAddressesResp
    example:
      network_addresses:
      - ip: ip
        roles:
        - roles
        - roles
        available: true
        host:
          name: name
          admin_ip: admin_ip
          id: 0
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        id: 0
        mask: 6
        network_interface:
          mac_address: mac_address
          name: name
          id: 1
      - ip: ip
        roles:
        - roles
        - roles
        available: true
        host:
          name: name
          admin_ip: admin_ip
          id: 0
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        id: 0
        mask: 6
        network_interface:
          mac_address: mac_address
          name: name
          id: 1
  NetworkAddressResp:
    type: object
    properties:
      network_address:
        description: network address record
        $ref: '#/definitions/NetworkAddress'
    title: NetworkAddressResp
    example:
      network_address:
        ip: ip
        roles:
        - roles
        - roles
        available: true
        host:
          name: name
          admin_ip: admin_ip
          id: 0
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        id: 0
        mask: 6
        network_interface:
          mac_address: mac_address
          name: name
          id: 1
  NetworkAddress:
    type: object
    properties:
      available:
        type: boolean
      create:
        type: string
        format: date-time
      host:
        $ref: '#/definitions/Host_Nestview'
      id:
        type: integer
        format: int64
      ip:
        type: string
      mask:
        type: integer
        format: int64
      network_interface:
        $ref: '#/definitions/NetworkInterface_Nestview'
      roles:
        type: array
        items:
          type: string
      update:
        type: string
        format: date-time
    title: NetworkAddress
    description: NetworkAddress defines model of network address @grpc-models-proto
    example:
      ip: ip
      roles:
      - roles
      - roles
      available: true
      host:
        name: name
        admin_ip: admin_ip
        id: 0
      create: '2000-01-23T04:56:07.000+00:00'
      update: '2000-01-23T04:56:07.000+00:00'
      id: 0
      mask: 6
      network_interface:
        mac_address: mac_address
        name: name
        id: 1
securityDefinitions:
  tokenInHeader:
    description: auth by token
    type: apiKey
    name: Xms-Auth-Token
    in: header
  tokenInQuery:
    description: auth by token
    type: apiKey
    name: token
    in: query
