openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Os Objects API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: os-objects
  description: OSObjectController Object Storage Object Management
paths:
  /os-objects/_search:
    get:
      tags:
      - os-objects
      description: List object storage objects by search
      operationId: ListOSObjectsBySearch
      responses:
        200:
          description: OK
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List OS objects by search
      x-summary-source: derived
    post:
      tags:
      - os-objects
      description: List object storage objects by search
      operationId: ListOSObjectsBySearch
      responses:
        200:
          description: OK
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List OS objects by search
      x-summary-source: derived
  /os-objects/_sql:
    get:
      tags:
      - os-objects
      description: List object storage objects by sql
      operationId: ListOSObjectsBySQL
      responses:
        200:
          description: OK
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List OS objects by SQL
      x-summary-source: derived
    post:
      tags:
      - os-objects
      description: List object storage objects by sql
      operationId: ListOSObjectsBySQL
      responses:
        200:
          description: OK
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List OS objects by SQL
      x-summary-source: derived
  /os-objects/report/_sql:
    get:
      tags:
      - os-objects
      description: Download object storage objects report by sql
      operationId: ReportOSObjectsBySQL
      parameters:
      - name: sql
        in: query
        description: select statement
        required: false
        x-exportParamName: Sql
        schema:
          type: string
      - name: os_buckets
        in: query
        description: name of buckets joined by colon
        required: false
        x-exportParamName: OsBuckets
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Report OS objects by SQL
      x-summary-source: derived
    post:
      tags:
      - os-objects
      description: Download object storage objects report by sql
      operationId: ReportOSObjectsBySQL
      parameters:
      - name: sql
        in: query
        description: select statement
        required: false
        x-exportParamName: Sql
        schema:
          type: string
      - name: os_buckets
        in: query
        description: name of buckets joined by colon
        required: false
        x-exportParamName: OsBuckets
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Report OS objects by SQL
      x-summary-source: derived
components:
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
