openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Fs Active Directories API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: fs-active-directories
  description: FSActiveDirectoryController File Storage Active Directory Management
paths:
  /fs-active-directories/:
    get:
      tags:
      - fs-active-directories
      description: List file storage active directories
      operationId: ListFSActiveDirectories
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSActiveDirectoriesResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List FS active directories
      x-summary-source: derived
    post:
      tags:
      - fs-active-directories
      description: create file storage active directory
      operationId: CreateFSActiveDirectory
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSActiveDirectoryResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSActiveDirectoryCreateReq'
        description: file storage active directory info
        required: true
      summary: Create FS active directory
      x-summary-source: derived
  /fs-active-directories/{fs_active_directory_id}:
    get:
      tags:
      - fs-active-directories
      description: Get a file storage active directory
      operationId: GetFSActiveDirectory
      parameters:
      - name: fs_active_directory_id
        in: path
        description: file storage active directory id
        required: true
        x-exportParamName: FsActiveDirectoryId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSActiveDirectoryResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get FS active directory
      x-summary-source: derived
    delete:
      tags:
      - fs-active-directories
      description: Delete file storage active directory
      operationId: DeleteFSActiveDirectory
      parameters:
      - name: fs_active_directory_id
        in: path
        description: file storage active directory id
        required: true
        x-exportParamName: FsActiveDirectoryId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSActiveDirectoryResp'
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete FS active directory
      x-summary-source: derived
    patch:
      tags:
      - fs-active-directories
      description: Update a file storage active directory
      operationId: UpdateFSActiveDirectory
      parameters:
      - name: fs_active_directory_id
        in: path
        description: file storage active directory id
        required: true
        x-exportParamName: FsActiveDirectoryId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSActiveDirectoryResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSActiveDirectoryUpdateReq'
        description: file storage active directory info
        required: true
      summary: Update FS active directory
      x-summary-source: derived
  /fs-active-directories/{fs_active_directory_id}:verify:
    post:
      tags:
      - fs-active-directories
      description: Verify a fs active directory or user/group info
      operationId: VerifyFSActiveDirectory
      parameters:
      - name: fs_active_directory_id
        in: path
        description: file storage active directory id
        required: true
        x-exportParamName: FsActiveDirectoryId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSActiveDirectoryResp'
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Verify FS active directory
      x-summary-source: derived
components:
  schemas:
    FSActiveDirectoryCreateReq:
      type: object
      required:
      - fs_active_directory
      properties:
        fs_active_directory:
          $ref: '#/components/schemas/FSActiveDirectoryCreateReq_Info'
      title: FSActiveDirectoryCreateReq
    FSActiveDirectoryCreateReq_Info:
      type: object
      required:
      - name
      - password
      - realm
      - username
      - workgroup
      properties:
        ip:
          type: string
          description: ip of dns server
        name:
          type: string
          description: name of active directory
        password:
          type: string
          description: password of active directory
        realm:
          type: string
          description: realm of active directory
        username:
          type: string
          description: username of active directory
        workgroup:
          type: string
          description: workgroup of active directory
      title: FSActiveDirectoryCreateReq_Info
    FSActiveDirectoryResp:
      type: object
      required:
      - fs_active_directory
      properties:
        fs_active_directory:
          description: file storage active directory
          $ref: '#/components/schemas/FSActiveDirectory'
      title: FSActiveDirectoryResp
      example:
        fs_active_directory:
          workgroup: workgroup
          ip: ip
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          fs_gateway_group_num: 0
          realm: realm
          id: 6
          verify_time: '2000-01-23T04:56:07.000+00:00'
          action_status: action_status
          status: status
          username: username
    FSActiveDirectoryUpdateReq:
      type: object
      required:
      - fs_active_directory
      properties:
        fs_active_directory:
          $ref: '#/components/schemas/FSActiveDirectoryUpdateReq_Info'
      title: FSActiveDirectoryUpdateReq
    FSActiveDirectoriesResp:
      type: object
      required:
      - fs_active_directories
      properties:
        fs_active_directories:
          type: array
          description: file storage active directories
          items:
            $ref: '#/components/schemas/FSActiveDirectory'
      title: FSActiveDirectoriesResp
      example:
        fs_active_directories:
        - workgroup: workgroup
          ip: ip
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          fs_gateway_group_num: 0
          realm: realm
          id: 6
          verify_time: '2000-01-23T04:56:07.000+00:00'
          action_status: action_status
          status: status
          username: username
        - workgroup: workgroup
          ip: ip
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          fs_gateway_group_num: 0
          realm: realm
          id: 6
          verify_time: '2000-01-23T04:56:07.000+00:00'
          action_status: action_status
          status: status
          username: username
    FSActiveDirectory:
      type: object
      properties:
        action_status:
          type: string
        create:
          type: string
          format: date-time
        fs_gateway_group_num:
          type: integer
          format: int64
        id:
          type: integer
          format: int64
        ip:
          type: string
        name:
          type: string
        realm:
          type: string
        status:
          type: string
        update:
          type: string
          format: date-time
        username:
          type: string
        verify_time:
          type: string
          format: date-time
        workgroup:
          type: string
      title: FSActiveDirectory
      description: FSActiveDirectory defines file storage active directory
      example:
        workgroup: workgroup
        ip: ip
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        fs_gateway_group_num: 0
        realm: realm
        id: 6
        verify_time: '2000-01-23T04:56:07.000+00:00'
        action_status: action_status
        status: status
        username: username
    FSActiveDirectoryUpdateReq_Info:
      type: object
      properties:
        ip:
          type: string
          description: ip of dns server
        name:
          type: string
          description: name of active directory
        password:
          type: string
          description: password of active directory
        realm:
          type: string
          description: realm of active directory
        username:
          type: string
          description: username of active directory
        workgroup:
          type: string
          description: workgroup of active directory
      title: FSActiveDirectoryUpdateReq_Info
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
