swagger: '2.0'
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS access-paths os-remote-policies API
  contact: {}
  license:
    name: Commercial
basePath: /v1
tags:
- name: os-remote-policies
  description: 'OSRemotePolicyController API /os-remote-policies

    '
paths:
  /os-remote-policies/:
    get:
      tags:
      - os-remote-policies
      description: List os remote policies
      operationId: ListOSRemotePolicies
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        type: integer
        format: int64
        x-exportParamName: Limit
      - name: offset
        in: query
        description: paging param
        required: false
        type: integer
        format: int64
        x-exportParamName: Offset
      - name: marker
        in: query
        description: paging param
        required: false
        type: string
        x-exportParamName: Marker
      - name: zone_uuid
        in: query
        description: zone uuid
        required: false
        type: string
        x-exportParamName: ZoneUuid
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/OSRemotePoliciesResp'
      security:
      - tokenInQuery: []
      - tokenInHeader: []
  /os-remote-policies/{policy_uuid}:
    get:
      tags:
      - os-remote-policies
      description: Get a os remote policy
      operationId: GetOSRemotePolicy
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: policy_uuid
        in: path
        description: policy uuid
        required: true
        type: string
        x-exportParamName: PolicyUuid
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/OSRemotePolicyResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
definitions:
  OSRemotePolicy:
    type: object
    properties:
      create:
        type: string
        format: date-time
      default:
        type: boolean
      name:
        type: string
      status:
        type: string
      update:
        type: string
        format: date-time
      uuid:
        type: string
      zone_uuid:
        type: string
    title: OSRemotePolicy
    description: OSRemotePolicy defines model of cached remote os policy.
    example:
      default: true
      name: name
      create: '2000-01-23T04:56:07.000+00:00'
      update: '2000-01-23T04:56:07.000+00:00'
      zone_uuid: zone_uuid
      uuid: uuid
      status: status
  OSRemotePolicyResp:
    type: object
    properties:
      os_remote_policy:
        $ref: '#/definitions/OSRemotePolicy'
    title: OSRemotePolicyResp
    example:
      os_remote_policy:
        default: true
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        zone_uuid: zone_uuid
        uuid: uuid
        status: status
  OSRemotePoliciesResp:
    type: object
    properties:
      os_remote_policies:
        type: array
        items:
          $ref: '#/definitions/OSRemotePolicy'
    title: OSRemotePoliciesResp
    example:
      os_remote_policies:
      - default: true
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        zone_uuid: zone_uuid
        uuid: uuid
        status: status
      - default: true
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        zone_uuid: zone_uuid
        uuid: uuid
        status: status
securityDefinitions:
  tokenInHeader:
    description: auth by token
    type: apiKey
    name: Xms-Auth-Token
    in: header
  tokenInQuery:
    description: auth by token
    type: apiKey
    name: token
    in: query
