openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Licenses API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: Licenses
  description: LicenseController Operations about Install
paths:
  /licenses/:
    get:
      tags:
      - Licenses
      operationId: ListLicenses
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      - name: active
        in: query
        description: filter license by active status
        required: false
        x-exportParamName: Active
        schema:
          type: boolean
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicensesResp'
        500:
          description: InternalServerError
      summary: List licenses
      x-summary-source: derived
    post:
      tags:
      - Licenses
      description: Activate product license
      operationId: RegisterLicense
      parameters:
      - name: force
        in: query
        description: force activate
        required: false
        x-exportParamName: Force
        schema:
          type: boolean
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicenseResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                license:
                  type: string
                  description: license info
                  format: binary
              required:
              - license
      summary: Register license
      x-summary-source: derived
  /licenses/key:
    get:
      tags:
      - Licenses
      description: get license key file
      operationId: DownloadLicenseKey
      responses:
        200:
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        404:
          description: NotFound
        500:
          description: InternalServerError
      summary: Download license key
      x-summary-source: derived
  /licenses/license:
    get:
      tags:
      - Licenses
      description: get current active license
      operationId: GetActiveLicense
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicenseResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get active license
      x-summary-source: derived
  /licenses/{license_id}:
    get:
      tags:
      - Licenses
      description: get license
      operationId: GetLicense
      parameters:
      - name: license_id
        in: path
        description: the license id
        required: true
        x-exportParamName: LicenseId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicenseResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get license
      x-summary-source: derived
components:
  schemas:
    LicensesResp:
      type: object
      required:
      - licenses
      properties:
        licenses:
          type: array
          description: licenses
          items:
            $ref: '#/components/schemas/License'
      title: LicensesResp
      example:
        licenses:
        - signed_time: '2000-01-23T04:56:07.000+00:00'
          used_capacity: 6
          used_host_num: 1
          active: true
          expired_time: '2000-01-23T04:56:07.000+00:00'
          product_info:
            series: series
            model: model
          services:
          - start_time: '2000-01-23T04:56:07.000+00:00'
            name: name
            expired_time: '2000-01-23T04:56:07.000+00:00'
          - start_time: '2000-01-23T04:56:07.000+00:00'
            name: name
            expired_time: '2000-01-23T04:56:07.000+00:00'
          uuid: uuid
          version: version
          features:
          - functions:
            - functions
            - functions
            name: name
            protocols:
            - protocols
            - protocols
            limits:
              key: limits
          - functions:
            - functions
            - functions
            name: name
            protocols:
            - protocols
            - protocols
            limits:
              key: limits
          create: '2000-01-23T04:56:07.000+00:00'
          id: 0
          limits: {}
          customer: customer
          status: status
        - signed_time: '2000-01-23T04:56:07.000+00:00'
          used_capacity: 6
          used_host_num: 1
          active: true
          expired_time: '2000-01-23T04:56:07.000+00:00'
          product_info:
            series: series
            model: model
          services:
          - start_time: '2000-01-23T04:56:07.000+00:00'
            name: name
            expired_time: '2000-01-23T04:56:07.000+00:00'
          - start_time: '2000-01-23T04:56:07.000+00:00'
            name: name
            expired_time: '2000-01-23T04:56:07.000+00:00'
          uuid: uuid
          version: version
          features:
          - functions:
            - functions
            - functions
            name: name
            protocols:
            - protocols
            - protocols
            limits:
              key: limits
          - functions:
            - functions
            - functions
            name: name
            protocols:
            - protocols
            - protocols
            limits:
              key: limits
          create: '2000-01-23T04:56:07.000+00:00'
          id: 0
          limits: {}
          customer: customer
          status: status
    LicenseResp:
      type: object
      required:
      - license
      properties:
        license:
          description: license
          $ref: '#/components/schemas/License'
      title: LicenseResp
      example:
        license:
          signed_time: '2000-01-23T04:56:07.000+00:00'
          used_capacity: 6
          used_host_num: 1
          active: true
          expired_time: '2000-01-23T04:56:07.000+00:00'
          product_info:
            series: series
            model: model
          services:
          - start_time: '2000-01-23T04:56:07.000+00:00'
            name: name
            expired_time: '2000-01-23T04:56:07.000+00:00'
          - start_time: '2000-01-23T04:56:07.000+00:00'
            name: name
            expired_time: '2000-01-23T04:56:07.000+00:00'
          uuid: uuid
          version: version
          features:
          - functions:
            - functions
            - functions
            name: name
            protocols:
            - protocols
            - protocols
            limits:
              key: limits
          - functions:
            - functions
            - functions
            name: name
            protocols:
            - protocols
            - protocols
            limits:
              key: limits
          create: '2000-01-23T04:56:07.000+00:00'
          id: 0
          limits: {}
          customer: customer
          status: status
    ProductFeature:
      type: object
      properties:
        functions:
          type: array
          items:
            type: string
        limits:
          type: object
          description: for viewing only
          additionalProperties:
            type: string
        name:
          type: string
        protocols:
          type: array
          items:
            type: string
      title: ProductFeature
      description: ProductFeature defines product feature
      example:
        functions:
        - functions
        - functions
        name: name
        protocols:
        - protocols
        - protocols
        limits:
          key: limits
    ProductLimits:
      type: object
      description: ProductLimits defines product limits
      additionalProperties:
        type: string
    ProductInfo:
      type: object
      properties:
        model:
          type: string
        series:
          type: string
      title: ProductInfo
      description: ProductInfo defines product info
      example:
        series: series
        model: model
    License:
      type: object
      properties:
        active:
          type: boolean
        create:
          type: string
          format: date-time
        customer:
          type: string
        expired_time:
          type: string
          format: date-time
        features:
          type: array
          items:
            $ref: '#/components/schemas/ProductFeature'
        id:
          type: integer
          format: int64
        limits:
          $ref: '#/components/schemas/ProductLimits'
        product_info:
          $ref: '#/components/schemas/ProductInfo'
        services:
          type: array
          items:
            $ref: '#/components/schemas/ProductService'
        signed_time:
          type: string
          format: date-time
        status:
          type: string
        used_capacity:
          type: integer
          format: int64
        used_host_num:
          type: integer
          format: int64
        uuid:
          type: string
        version:
          type: string
          description: v2, load from license info
      title: License
      description: License is used to manage backend license @grpc-models-proto
      example:
        signed_time: '2000-01-23T04:56:07.000+00:00'
        used_capacity: 6
        used_host_num: 1
        active: true
        expired_time: '2000-01-23T04:56:07.000+00:00'
        product_info:
          series: series
          model: model
        services:
        - start_time: '2000-01-23T04:56:07.000+00:00'
          name: name
          expired_time: '2000-01-23T04:56:07.000+00:00'
        - start_time: '2000-01-23T04:56:07.000+00:00'
          name: name
          expired_time: '2000-01-23T04:56:07.000+00:00'
        uuid: uuid
        version: version
        features:
        - functions:
          - functions
          - functions
          name: name
          protocols:
          - protocols
          - protocols
          limits:
            key: limits
        - functions:
          - functions
          - functions
          name: name
          protocols:
          - protocols
          - protocols
          limits:
            key: limits
        create: '2000-01-23T04:56:07.000+00:00'
        id: 0
        limits: {}
        customer: customer
        status: status
    ProductService:
      type: object
      properties:
        expired_time:
          type: string
          format: date-time
        name:
          type: string
        start_time:
          type: string
          format: date-time
      title: ProductService
      description: ProductService defines product service
      example:
        start_time: '2000-01-23T04:56:07.000+00:00'
        name: name
        expired_time: '2000-01-23T04:56:07.000+00:00'
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
