openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Chunks API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: Chunks
  description: ChunkController Chunk Management
paths:
  /chunks/{chunk_id}:
    get:
      tags:
      - Chunks
      description: get an chunk
      operationId: GetChunk
      parameters:
      - name: chunk_id
        in: path
        description: The id of the chunk
        required: true
        x-exportParamName: ChunkId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: '{models.PlacementGroup}'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get chunk
      x-summary-source: derived
components:
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
