openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Fs Ftp Share Acls API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: fs-ftp-share-acls
  description: FSFTPShareACLController provides API for fs ftp share acl
paths:
  /fs-ftp-share-acls/:
    get:
      tags:
      - fs-ftp-share-acls
      description: List fs ftp share acls
      operationId: ListFSFTPShareACLs
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: fs_ftp_share_id
        in: query
        description: fs ftp share id
        required: false
        x-exportParamName: FsFtpShareId
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSFTPShareACLsResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List FSFTP share ACLs
      x-summary-source: derived
components:
  schemas:
    FSFTPShare_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
      title: FSFTPShare_Nestview
      example:
        id: 6
    FSUserGroup_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: FSUserGroup_Nestview
      example:
        name: name
        id: 1
    FSUser_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: FSUser_Nestview
      example:
        name: name
        id: 6
    FSFTPShareACLsResp:
      type: object
      required:
      - fs_ftp_share_acls
      properties:
        fs_ftp_share_acls:
          type: array
          description: fs ftp share acls
          items:
            $ref: '#/components/schemas/FSFTPShareACL'
      title: FSFTPShareACLsResp
      example:
        fs_ftp_share_acls:
        - download_enabled: true
          update: '2000-01-23T04:56:07.000+00:00'
          delete_enabled: true
          type: type
          download_bandwidth: 0
          fs_user_group:
            name: name
            id: 1
          rename_enabled: true
          fs_user:
            name: name
            id: 6
          upload_bandwidth: 5
          create: '2000-01-23T04:56:07.000+00:00'
          upload_enabled: true
          id: 5
          create_enabled: true
          fs_ftp_share:
            id: 6
          list_enabled: true
        - download_enabled: true
          update: '2000-01-23T04:56:07.000+00:00'
          delete_enabled: true
          type: type
          download_bandwidth: 0
          fs_user_group:
            name: name
            id: 1
          rename_enabled: true
          fs_user:
            name: name
            id: 6
          upload_bandwidth: 5
          create: '2000-01-23T04:56:07.000+00:00'
          upload_enabled: true
          id: 5
          create_enabled: true
          fs_ftp_share:
            id: 6
          list_enabled: true
    FSFTPShareACL:
      type: object
      properties:
        create:
          type: string
          format: date-time
        create_enabled:
          type: boolean
        delete_enabled:
          type: boolean
        download_bandwidth:
          type: integer
          format: int64
        download_enabled:
          type: boolean
        fs_ftp_share:
          $ref: '#/components/schemas/FSFTPShare_Nestview'
        fs_user:
          $ref: '#/components/schemas/FSUser_Nestview'
        fs_user_group:
          $ref: '#/components/schemas/FSUserGroup_Nestview'
        id:
          type: integer
          format: int64
        list_enabled:
          type: boolean
        rename_enabled:
          type: boolean
        type:
          type: string
        update:
          type: string
          format: date-time
        upload_bandwidth:
          type: integer
          format: int64
        upload_enabled:
          type: boolean
      title: FSFTPShareACL
      description: FSFTPShareACL defines model of fs ftp share ACL
      example:
        download_enabled: true
        update: '2000-01-23T04:56:07.000+00:00'
        delete_enabled: true
        type: type
        download_bandwidth: 0
        fs_user_group:
          name: name
          id: 1
        rename_enabled: true
        fs_user:
          name: name
          id: 6
        upload_bandwidth: 5
        create: '2000-01-23T04:56:07.000+00:00'
        upload_enabled: true
        id: 5
        create_enabled: true
        fs_ftp_share:
          id: 6
        list_enabled: true
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
