openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Client Codes API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: client-codes
  description: ClientCodeController Operations about client code
paths:
  /client-codes/:
    get:
      tags:
      - client-codes
      description: List client iqns/wwns
      operationId: ListClientCodes
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: type
        in: query
        description: FC/iSCSI
        required: false
        x-exportParamName: Type_
        schema:
          type: string
      - name: unused
        in: query
        description: list unused client codes
        required: false
        x-exportParamName: Unused
        schema:
          type: boolean
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientCodesResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List client codes
      x-summary-source: derived
components:
  schemas:
    ClientCode:
      type: object
      properties:
        code:
          type: string
        create:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        type:
          type: string
      title: ClientCode
      example:
        code: code
        create: '2000-01-23T04:56:07.000+00:00'
        id: 0
        type: type
    ClientCodesResp:
      type: object
      required:
      - client_codes
      properties:
        client_codes:
          type: array
          description: client codes
          items:
            $ref: '#/components/schemas/ClientCode'
      title: ClientCodesResp
      example:
        client_codes:
        - code: code
          create: '2000-01-23T04:56:07.000+00:00'
          id: 0
          type: type
        - code: code
          create: '2000-01-23T04:56:07.000+00:00'
          id: 0
          type: type
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
