openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Dp Block Backup Policies API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: dp-block-backup-policies
  description: DpBlockBackupPolicyController API /dp-block-backup-policies
paths:
  /dp-block-backup-policies/:
    get:
      tags:
      - dp-block-backup-policies
      operationId: ListDpBlockBackupPolicies
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      - name: block_volume_id
        in: query
        description: show dp block backup policies of specific block volume
        required: false
        x-exportParamName: BlockVolumeId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpBlockBackupPoliciesResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List dp block backup policies
      x-summary-source: derived
    post:
      tags:
      - dp-block-backup-policies
      operationId: CreateDpBlockBackupPolicy
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpBlockBackupPolicyResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DpBlockBackupPolicyCreateReq'
        description: policy info
        required: true
      summary: Create dp block backup policy
      x-summary-source: derived
  /dp-block-backup-policies/{policy_id}:
    get:
      tags:
      - dp-block-backup-policies
      operationId: GetDpBlockBackupPolicy
      parameters:
      - name: policy_id
        in: path
        description: resource id
        required: true
        x-exportParamName: PolicyId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpBlockBackupPolicyResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get dp block backup policy
      x-summary-source: derived
    delete:
      tags:
      - dp-block-backup-policies
      operationId: DeleteDpBlockBackupPolicy
      parameters:
      - name: policy_id
        in: path
        description: resource id
        required: true
        x-exportParamName: PolicyId
        schema:
          type: integer
          format: int64
      - name: force
        in: query
        description: force delete or not
        required: false
        x-exportParamName: Force
        schema:
          type: boolean
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpBlockBackupPolicyResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete dp block backup policy
      x-summary-source: derived
    patch:
      tags:
      - dp-block-backup-policies
      operationId: UpdateDpBlockBackupPolicy
      parameters:
      - name: policy_id
        in: path
        description: resource id
        required: true
        x-exportParamName: PolicyId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpBlockBackupPolicyResp'
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DpBlockBackupPolicyResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DpBlockBackupPolicyUpdateReq'
        description: policy info
        required: true
      summary: Update dp block backup policy
      x-summary-source: derived
components:
  schemas:
    DpBlockBackupPolicyCreateReq_Policy:
      type: object
      required:
      - dp_gateway_id
      - dp_site_id
      - full_cron_expr
      - name
      - retained_max
      properties:
        dp_gateway_id:
          type: integer
          format: int64
          description: dp gateway
        dp_site_id:
          type: integer
          format: int64
          description: dp site
        encrypted:
          type: boolean
          description: encrypted or not
        full_cron_expr:
          type: string
          description: cron expression for full backup
        inc_cron_expr:
          type: string
          description: cron expression for increment backup
        name:
          type: string
          description: name
        retained_max:
          type: integer
          format: int64
          description: retained max number of backups
      title: DpBlockBackupPolicyCreateReq_Policy
      example:
        inc_cron_expr: inc_cron_expr
        retained_max: 1
        dp_gateway_id: 0
        encrypted: true
        full_cron_expr: full_cron_expr
        name: name
        dp_site_id: 6
    DpBlockBackupPolicyUpdateReq_Policy:
      type: object
      properties:
        encrypted:
          type: boolean
          description: encrypted or not
        full_cron_expr:
          type: string
          description: cron expression for full backup
        inc_cron_expr:
          type: string
          description: cron expression for increment backup
        name:
          type: string
          description: name
        retained_max:
          type: integer
          format: int64
          description: retained max number of backups
      title: DpBlockBackupPolicyUpdateReq_Policy
      example:
        inc_cron_expr: inc_cron_expr
        retained_max: 0
        encrypted: true
        full_cron_expr: full_cron_expr
        name: name
    DpBlockBackupPoliciesResp:
      type: object
      properties:
        dp_block_backup_policies:
          type: array
          items:
            $ref: '#/components/schemas/DpBlockBackupPolicy'
      title: DpBlockBackupPoliciesResp
      example:
        dp_block_backup_policies:
        - inc_cron_expr: inc_cron_expr
          retained_max: 5
          dp_site:
            name: name
            id: 1
          encrypted: true
          block_volume_num: 0
          full_cron_expr: full_cron_expr
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          dp_gateway:
            name: name
            id: 6
          id: 5
          status: status
        - inc_cron_expr: inc_cron_expr
          retained_max: 5
          dp_site:
            name: name
            id: 1
          encrypted: true
          block_volume_num: 0
          full_cron_expr: full_cron_expr
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          dp_gateway:
            name: name
            id: 6
          id: 5
          status: status
    DpSite_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: DpSite_Nestview
      example:
        name: name
        id: 1
    DpBlockBackupPolicyCreateReq:
      type: object
      required:
      - dp_block_backup_policy
      properties:
        dp_block_backup_policy:
          $ref: '#/components/schemas/DpBlockBackupPolicyCreateReq_Policy'
      title: DpBlockBackupPolicyCreateReq
      example:
        dp_block_backup_policy:
          inc_cron_expr: inc_cron_expr
          retained_max: 1
          dp_gateway_id: 0
          encrypted: true
          full_cron_expr: full_cron_expr
          name: name
          dp_site_id: 6
    DpBlockBackupPolicy:
      type: object
      properties:
        block_volume_num:
          type: integer
          format: int64
        create:
          type: string
          format: date-time
        dp_gateway:
          $ref: '#/components/schemas/DpGateway_Nestview'
        dp_site:
          $ref: '#/components/schemas/DpSite_Nestview'
        encrypted:
          type: boolean
        full_cron_expr:
          type: string
        id:
          type: integer
          format: int64
        inc_cron_expr:
          type: string
        name:
          type: string
        retained_max:
          type: integer
          format: int64
        status:
          type: string
        update:
          type: string
          format: date-time
      title: DpBlockBackupPolicy
      description: DpBlockBackupPolicy protects a block volume by backup snapshot to remote site
      example:
        inc_cron_expr: inc_cron_expr
        retained_max: 5
        dp_site:
          name: name
          id: 1
        encrypted: true
        block_volume_num: 0
        full_cron_expr: full_cron_expr
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        dp_gateway:
          name: name
          id: 6
        id: 5
        status: status
    DpBlockBackupPolicyUpdateReq:
      type: object
      required:
      - dp_block_backup_policy
      properties:
        dp_block_backup_policy:
          $ref: '#/components/schemas/DpBlockBackupPolicyUpdateReq_Policy'
      title: DpBlockBackupPolicyUpdateReq
      example:
        dp_block_backup_policy:
          inc_cron_expr: inc_cron_expr
          retained_max: 0
          encrypted: true
          full_cron_expr: full_cron_expr
          name: name
    DpBlockBackupPolicyResp:
      type: object
      properties:
        dp_block_backup_policy:
          $ref: '#/components/schemas/DpBlockBackupPolicy'
      title: DpBlockBackupPolicyResp
      example:
        dp_block_backup_policy:
          inc_cron_expr: inc_cron_expr
          retained_max: 5
          dp_site:
            name: name
            id: 1
          encrypted: true
          block_volume_num: 0
          full_cron_expr: full_cron_expr
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          dp_gateway:
            name: name
            id: 6
          id: 5
          status: status
    DpGateway_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: DpGateway_Nestview
      example:
        name: name
        id: 6
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
