openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Access Tokens API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: Access Tokens
  description: AccessTokenController Manage users
paths:
  /access-tokens/:
    get:
      tags:
      - Access Tokens
      operationId: ListAccessTokens
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: user_id
        in: query
        description: The id of user access tokens belong to
        required: false
        x-exportParamName: UserId
        schema:
          type: integer
          format: int64
      - name: role
        in: query
        description: filter access tokens by role
        required: false
        x-exportParamName: Role
        schema:
          type: string
      - name: all
        in: query
        description: show all access tokens
        required: false
        x-exportParamName: All
        schema:
          type: boolean
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokensResp'
        403:
          description: Forbidden
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      summary: List access tokens
      x-summary-source: derived
    post:
      tags:
      - Access Tokens
      description: Create an access token
      operationId: CreateAccessToken
      responses:
        201:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenCreateResp'
        400:
          description: BadRequest
        403:
          description: Forbidden
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessTokenCreateReq'
        description: access token info
        required: true
      summary: Create access token
      x-summary-source: derived
  /access-tokens/{access_token_id}:
    get:
      tags:
      - Access Tokens
      description: get an access Token
      operationId: GetAccessToken
      parameters:
      - name: access_token_id
        in: path
        description: access token id
        required: true
        x-exportParamName: AccessTokenId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResp'
        403:
          description: Forbidden
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get access token
      x-summary-source: derived
    delete:
      tags:
      - Access Tokens
      description: delete an access token
      operationId: DeleteAccessToken
      parameters:
      - name: access_token_id
        in: path
        description: access token id
        required: true
        x-exportParamName: AccessTokenId
        schema:
          type: integer
          format: int64
      responses:
        204:
          description: No Content
        403:
          description: Forbidden
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete access token
      x-summary-source: derived
    patch:
      tags:
      - Access Tokens
      description: update an access token
      operationId: UpdateAccessToken
      parameters:
      - name: access_token_id
        in: path
        description: access token id
        required: true
        x-exportParamName: AccessTokenId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessTokenUpdateReq'
        description: access token info
        required: true
      summary: Update access token
      x-summary-source: derived
  /access-tokens/{access_token_id}:regenerate:
    post:
      tags:
      - Access Tokens
      description: regenereate an access token UUID
      operationId: RegenerateAccessToken
      parameters:
      - name: access_token_id
        in: path
        description: access token id
        required: true
        x-exportParamName: AccessTokenId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenCreateResp'
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Regenerate access token
      x-summary-source: derived
  /access-tokens:validate:
    post:
      tags:
      - Access Tokens
      description: validate an access token
      operationId: ValidateAccessToken
      parameters:
      - name: subject_access_token
        in: query
        description: access token to be validated
        required: true
        x-exportParamName: SubjectAccessToken
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResp'
        400:
          description: BadRequest
        403:
          description: Forbidden
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Validate access token
      x-summary-source: derived
components:
  schemas:
    User_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: id of user
        name:
          type: string
          description: name of user
      title: User_Nestview
      example:
        name: name
        id: 6
    AccessTokenUpdateReq_AccessToken:
      type: object
      required:
      - name
      properties:
        name:
          type: string
          description: name of access token
      title: AccessTokenUpdateReq_AccessToken
      example:
        name: name
    AccessTokenUpdateReq:
      type: object
      properties:
        access_token:
          $ref: '#/components/schemas/AccessTokenUpdateReq_AccessToken'
      title: AccessTokenUpdateReq
      example:
        access_token:
          name: name
    AccessTokenCreateResp:
      type: object
      required:
      - access_token
      properties:
        access_token:
          description: access token
          $ref: '#/components/schemas/AccessTokenCreateRecord'
      title: AccessTokenCreateResp
      example:
        access_token: ''
    AccessTokenCreateRecord:
      title: AccessTokenCreateRecord
      allOf:
      - $ref: '#/components/schemas/AccessToken'
      - properties:
          uuid:
            type: string
      description: AccessTokenCreateRecord defines access token record for creating api response
    AccessTokensResp:
      type: object
      required:
      - access_tokens
      properties:
        access_tokens:
          type: array
          description: access tokens
          items:
            $ref: '#/components/schemas/AccessToken'
      title: AccessTokensResp
      example:
        access_tokens:
        - roles:
          - roles
          - roles
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          description: description
          update: '2000-01-23T04:56:07.000+00:00'
          id: 0
          used: true
          user:
            name: name
            id: 6
        - roles:
          - roles
          - roles
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          description: description
          update: '2000-01-23T04:56:07.000+00:00'
          id: 0
          used: true
          user:
            name: name
            id: 6
    AccessTokenResp:
      type: object
      properties:
        access_token:
          description: access token
          $ref: '#/components/schemas/AccessToken'
      title: AccessTokenResp
      example:
        access_token:
          roles:
          - roles
          - roles
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          description: description
          update: '2000-01-23T04:56:07.000+00:00'
          id: 0
          used: true
          user:
            name: name
            id: 6
    AccessToken:
      type: object
      properties:
        create:
          type: string
          format: date-time
        description:
          type: string
        id:
          type: integer
          format: int64
        name:
          type: string
        roles:
          type: array
          items:
            type: string
        update:
          type: string
          format: date-time
        used:
          type: boolean
        user:
          $ref: '#/components/schemas/User_Nestview'
      title: AccessToken
      description: AccessToken used for authentication and authorization
      example:
        roles:
        - roles
        - roles
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        description: description
        update: '2000-01-23T04:56:07.000+00:00'
        id: 0
        used: true
        user:
          name: name
          id: 6
    AccessTokenCreateReq:
      type: object
      properties:
        access_token:
          $ref: '#/components/schemas/AccessTokenCreateReq_AccessToken'
      title: AccessTokenCreateReq
      example:
        access_token:
          roles:
          - roles
          - roles
          name: name
          description: description
    AccessTokenCreateReq_AccessToken:
      type: object
      required:
      - name
      - roles
      properties:
        description:
          type: string
          description: description of access token
        name:
          type: string
          description: name of access token
        roles:
          type: array
          description: roles of access token
          items:
            type: string
      title: AccessTokenCreateReq_AccessToken
      example:
        roles:
        - roles
        - roles
        name: name
        description: description
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
