swagger: '2.0'
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS access-paths host-info API
  contact: {}
  license:
    name: Commercial
basePath: /v1
tags:
- name: host-info
  description: 'HostInfoController Host Info Management

    '
paths:
  /host-info/:
    get:
      tags:
      - host-info
      description: scan host info from specified ip
      operationId: GetHostInfo
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: ip
        in: query
        description: host ip
        required: true
        type: string
        x-exportParamName: Ip
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/HostInfoResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
definitions:
  HostInfoResp:
    type: object
    required:
    - host_info
    properties:
      host_info:
        description: host info
        $ref: '#/definitions/HostInfo'
    title: HostInfoResp
    example:
      host_info:
        ips:
        - ips
        - ips
  HostInfo:
    type: object
    properties:
      ips:
        type: array
        items:
          type: string
    title: HostInfo
    example:
      ips:
      - ips
      - ips
securityDefinitions:
  tokenInHeader:
    description: auth by token
    type: apiKey
    name: Xms-Auth-Token
    in: header
  tokenInQuery:
    description: auth by token
    type: apiKey
    name: token
    in: query
