swagger: '2.0'
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS access-paths dp-block-snapshot-jobs API
  contact: {}
  license:
    name: Commercial
basePath: /v1
tags:
- name: dp-block-snapshot-jobs
  description: 'DpBlockSnapshotJobController API /dp-block-snapshot-jobs/

    '
paths:
  /dp-block-snapshot-jobs/:
    get:
      tags:
      - dp-block-snapshot-jobs
      description: List dp block snapshot jobs
      operationId: ListDpBlockSnapshotJobs
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        type: integer
        format: int64
        x-exportParamName: Limit
      - name: offset
        in: query
        description: paging param
        required: false
        type: integer
        format: int64
        x-exportParamName: Offset
      - name: q
        in: query
        description: query param of search
        required: false
        type: string
        x-exportParamName: Q
      - name: sort
        in: query
        description: sort param of search
        required: false
        type: string
        x-exportParamName: Sort
      - name: block_volume_id
        in: query
        description: block volume
        required: false
        type: integer
        format: int64
        x-exportParamName: BlockVolumeId
      - name: block_snapshot_id
        in: query
        description: object storage bucket
        required: false
        type: integer
        format: int64
        x-exportParamName: BlockSnapshotId
      - name: dp_block_snapshot_policy_id
        in: query
        description: dp block snapshot policy
        required: false
        type: integer
        format: int64
        x-exportParamName: DpBlockSnapshotPolicyId
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/DpBlockSnapshotJobsResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
definitions:
  DpBlockSnapshotJob:
    type: object
    properties:
      block_snapshot:
        $ref: '#/definitions/Snapshot_Nestview'
      block_volume:
        $ref: '#/definitions/Volume_Nestview'
      block_volume_size:
        type: integer
        format: int64
      diff_type:
        type: string
      dp_block_snapshot_policy:
        $ref: '#/definitions/DpBlockSnapshotPolicy_Nestview'
      finished_at:
        type: string
        format: date-time
      id:
        type: integer
        format: int64
      progress:
        type: number
        format: double
      size:
        type: integer
        format: int64
      started_at:
        type: string
        format: date-time
      status:
        type: string
      updated_at:
        type: string
        format: date-time
    title: DpBlockSnapshotJob
    description: DpBlockSnapshotJob is one execution of a dp block snapshot plan
    example:
      block_volume_size: 0
      finished_at: '2000-01-23T04:56:07.000+00:00'
      size: 5
      updated_at: '2000-01-23T04:56:07.000+00:00'
      diff_type: diff_type
      dp_block_snapshot_policy:
        name: name
        id: 6
      block_volume:
        original_name: original_name
        name: name
        id: 9
      progress: 5.962133916683182
      started_at: '2000-01-23T04:56:07.000+00:00'
      id: 1
      block_snapshot:
        name: name
        id: 0
      status: status
  Snapshot_Nestview:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    title: Snapshot_Nestview
    example:
      name: name
      id: 0
  DpBlockSnapshotPolicy_Nestview:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    title: DpBlockSnapshotPolicy_Nestview
    example:
      name: name
      id: 6
  DpBlockSnapshotJobsResp:
    type: object
    required:
    - dp_block_snapshot_jobs
    properties:
      dp_block_snapshot_jobs:
        type: array
        items:
          $ref: '#/definitions/DpBlockSnapshotJob'
    title: DpBlockSnapshotJobsResp
    example:
      dp_block_snapshot_jobs:
      - block_volume_size: 0
        finished_at: '2000-01-23T04:56:07.000+00:00'
        size: 5
        updated_at: '2000-01-23T04:56:07.000+00:00'
        diff_type: diff_type
        dp_block_snapshot_policy:
          name: name
          id: 6
        block_volume:
          original_name: original_name
          name: name
          id: 9
        progress: 5.962133916683182
        started_at: '2000-01-23T04:56:07.000+00:00'
        id: 1
        block_snapshot:
          name: name
          id: 0
        status: status
      - block_volume_size: 0
        finished_at: '2000-01-23T04:56:07.000+00:00'
        size: 5
        updated_at: '2000-01-23T04:56:07.000+00:00'
        diff_type: diff_type
        dp_block_snapshot_policy:
          name: name
          id: 6
        block_volume:
          original_name: original_name
          name: name
          id: 9
        progress: 5.962133916683182
        started_at: '2000-01-23T04:56:07.000+00:00'
        id: 1
        block_snapshot:
          name: name
          id: 0
        status: status
  Volume_Nestview:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      original_name:
        type: string
    title: Volume_Nestview
    example:
      original_name: original_name
      name: name
      id: 9
securityDefinitions:
  tokenInHeader:
    description: auth by token
    type: apiKey
    name: Xms-Auth-Token
    in: header
  tokenInQuery:
    description: auth by token
    type: apiKey
    name: token
    in: query
