openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Partitions API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: Partitions
  description: PartitionController API /partitions.
paths:
  /partitions/:
    get:
      tags:
      - Partitions
      operationId: ListPartitions
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      - name: host_id
        in: query
        description: host id
        required: false
        x-exportParamName: HostId
        schema:
          type: integer
          format: int64
      - name: disk_id
        in: query
        description: disk id
        required: false
        x-exportParamName: DiskId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartitionsResp'
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      summary: List partitions
      x-summary-source: derived
  /partitions/{partition_id}:
    get:
      tags:
      - Partitions
      description: Get a partition info
      operationId: GetPartition
      parameters:
      - name: partition_id
        in: path
        description: partition id
        required: true
        x-exportParamName: PartitionId
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartitionResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      summary: Get partition
      x-summary-source: derived
components:
  schemas:
    Disk_Nestview:
      type: object
      properties:
        device:
          type: string
        disk_type:
          type: string
        id:
          type: integer
          format: int64
      title: Disk_Nestview
      example:
        disk_type: disk_type
        id: 0
        device: device
    PartitionResp:
      type: object
      properties:
        partition:
          $ref: '#/components/schemas/Partition'
      title: PartitionResp
      example:
        partition:
          omap_device_path: omap_device_path
          update: '2000-01-23T04:56:07.000+00:00'
          omap_byte: 1
          used: true
          uuid: uuid
          version: 5
          path: path
          disk:
            disk_type: disk_type
            id: 0
            device: device
          size: 5
          create: '2000-01-23T04:56:07.000+00:00'
          id: 6
          action_status: action_status
          status: status
    Partition:
      type: object
      properties:
        action_status:
          type: string
        create:
          type: string
          format: date-time
        disk:
          $ref: '#/components/schemas/Disk_Nestview'
        id:
          type: integer
          format: int64
        omap_byte:
          type: integer
          format: int64
        omap_device_path:
          type: string
        path:
          type: string
        size:
          type: integer
          format: int64
        status:
          type: string
        update:
          type: string
          format: date-time
        used:
          type: boolean
        uuid:
          type: string
        version:
          type: integer
          format: int64
      title: Partition
      description: Partition defines cache partition of disk
      example:
        omap_device_path: omap_device_path
        update: '2000-01-23T04:56:07.000+00:00'
        omap_byte: 1
        used: true
        uuid: uuid
        version: 5
        path: path
        disk:
          disk_type: disk_type
          id: 0
          device: device
        size: 5
        create: '2000-01-23T04:56:07.000+00:00'
        id: 6
        action_status: action_status
        status: status
    PartitionsResp:
      type: object
      properties:
        partitions:
          type: array
          items:
            $ref: '#/components/schemas/Partition'
      title: PartitionsResp
      example:
        partitions:
        - omap_device_path: omap_device_path
          update: '2000-01-23T04:56:07.000+00:00'
          omap_byte: 1
          used: true
          uuid: uuid
          version: 5
          path: path
          disk:
            disk_type: disk_type
            id: 0
            device: device
          size: 5
          create: '2000-01-23T04:56:07.000+00:00'
          id: 6
          action_status: action_status
          status: status
        - omap_device_path: omap_device_path
          update: '2000-01-23T04:56:07.000+00:00'
          omap_byte: 1
          used: true
          uuid: uuid
          version: 5
          path: path
          disk:
            disk_type: disk_type
            id: 0
            device: device
          size: 5
          create: '2000-01-23T04:56:07.000+00:00'
          id: 6
          action_status: action_status
          status: status
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
