openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Fs Smb Shares API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: fs-smb-shares
  description: FSSMBShareController provides API for fs smb share
paths:
  /fs-smb-shares/:
    get:
      tags:
      - fs-smb-shares
      description: List fs smb shares
      operationId: ListFSSMBShares
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: fs_folder_id
        in: query
        description: fs folder id
        required: false
        x-exportParamName: FsFolderId
        schema:
          type: integer
          format: int64
      - name: fs_gateway_group_id
        in: query
        description: fs gateway group id
        required: false
        x-exportParamName: FsGatewayGroupId
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSSMBSharesResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List FSSMB shares
      x-summary-source: derived
    post:
      tags:
      - fs-smb-shares
      description: Create fs smb share
      operationId: CreateFSSMBShare
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSSMBShareResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSSMBShareCreateReq'
        description: share info
        required: true
      summary: Create FSSMB share
      x-summary-source: derived
  /fs-smb-shares/{fs_smb_share_id}:
    get:
      tags:
      - fs-smb-shares
      description: Get fs smb share
      operationId: GetFSSMBShare
      parameters:
      - name: fs_smb_share_id
        in: path
        description: share id
        required: true
        x-exportParamName: FsSmbShareId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSSMBShareResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get FSSMB share
      x-summary-source: derived
    delete:
      tags:
      - fs-smb-shares
      description: delete fs smb share
      operationId: DeleteFSSMBShare
      parameters:
      - name: fs_smb_share_id
        in: path
        description: share id
        required: true
        x-exportParamName: FsSmbShareId
        schema:
          type: integer
          format: int64
      - name: force
        in: query
        description: force delete or not
        required: false
        x-exportParamName: Force
        schema:
          type: boolean
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSSMBShareResp'
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete FSSMB share
      x-summary-source: derived
    patch:
      tags:
      - fs-smb-shares
      description: Update fs smb share
      operationId: UpdateFSSMBShare
      parameters:
      - name: fs_smb_share_id
        in: path
        description: share id
        required: true
        x-exportParamName: FsSmbShareId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSSMBShareResp'
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSSMBShareResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSSMBShareUpdateReq'
        description: share info
        required: true
      summary: Update FSSMB share
      x-summary-source: derived
  /fs-smb-shares/{fs_smb_share_id}:add-acls:
    post:
      tags:
      - fs-smb-shares
      description: Add fs smb share acls
      operationId: AddFSSMBShareACLs
      parameters:
      - name: fs_smb_share_id
        in: path
        description: fs smb share id
        required: true
        x-exportParamName: FsSmbShareId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSSMBShareResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSSMBShareAddACLsReq'
        description: share acls info
        required: true
      summary: Add FSSMB share ACLs
      x-summary-source: derived
  /fs-smb-shares/{fs_smb_share_id}:remove-acls:
    post:
      tags:
      - fs-smb-shares
      description: remove fs smb share acls
      operationId: RemoveFSSMBShareACLs
      parameters:
      - name: fs_smb_share_id
        in: path
        description: fs smb share id
        required: true
        x-exportParamName: FsSmbShareId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSSMBShareResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSSMBShareRemoveACLsReq'
        description: share acls info
        required: true
      summary: Remove FSSMB share ACLs
      x-summary-source: derived
  /fs-smb-shares/{fs_smb_share_id}:update-acls:
    post:
      tags:
      - fs-smb-shares
      description: Update fs smb share ACL
      operationId: UpdateFSSMBShareACLs
      parameters:
      - name: fs_smb_share_id
        in: path
        description: share id
        required: true
        x-exportParamName: FsSmbShareId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSSMBShareResp'
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSSMBShareResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSSMBShareUpdateACLsReq'
        description: share acls info
        required: true
      summary: Update FSSMB share ACLs
      x-summary-source: derived
components:
  schemas:
    FSGatewayGroup_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        vip:
          type: string
        vip_mask:
          type: integer
          format: int64
      title: FSGatewayGroup_Nestview
      example:
        name: name
        id: 6
        vip_mask: 1
        vip: vip
    FSSMBShareCreateReq_Share:
      type: object
      required:
      - fs_folder_id
      - fs_gateway_group_id
      properties:
        acl_inherited:
          type: boolean
          description: default acl status
        case_sensitive:
          type: boolean
          description: case sensitive
        fs_folder_id:
          type: integer
          format: int64
          description: folder id
        fs_gateway_group_id:
          type: integer
          format: int64
          description: gateway group id
        fs_quota_tree_id:
          type: integer
          format: int64
          description: quota tree id
        fs_smb_share_acls:
          type: array
          description: access control array
          items:
            $ref: '#/components/schemas/FSSMBShareACLReq'
        name:
          type: string
          description: name of share
        recycled:
          type: boolean
          description: recycle status
      title: FSSMBShareCreateReq_Share
    FSSMBShareRemoveACLsReq:
      type: object
      required:
      - fs_smb_share
      properties:
        fs_smb_share:
          $ref: '#/components/schemas/FSSMBShareRemoveACLsReq_Share'
      title: FSSMBShareRemoveACLsReq
    FSSMBShareUpdateACLsReq_Share:
      type: object
      properties:
        fs_smb_share_acls:
          type: array
          description: access control array
          items:
            $ref: '#/components/schemas/FSSMBShareUpdateACLReq'
      title: FSSMBShareUpdateACLsReq_Share
    FSSMBShareACLReq:
      type: object
      properties:
        fs_user_group_id:
          type: integer
          format: int64
          description: id of user group
        fs_user_group_name:
          type: string
          description: id of user group
        fs_user_id:
          type: integer
          format: int64
          description: id of user
        fs_user_name:
          type: string
          description: id of user
        id:
          type: integer
          format: int64
          description: id of user group
        permission:
          type: string
          description: readonly or readwrite access
        type:
          type: string
          description: type of share acl
      title: FSSMBShareACLReq
    FSSMBShareUpdateACLReq:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: id of user group
        permission:
          type: string
          description: readonly or readwrite access
      title: FSSMBShareUpdateACLReq
    FSFolder_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: FSFolder_Nestview
      example:
        name: name
        id: 6
    FSSMBShareAddACLsReq_Share:
      type: object
      required:
      - fs_smb_share_acls
      properties:
        fs_smb_share_acls:
          type: array
          description: access control array
          items:
            $ref: '#/components/schemas/FSSMBShareACLReq'
      title: FSSMBShareAddACLsReq_Share
    FSSMBShareUpdateReq_Share:
      type: object
      properties:
        acl_inherited:
          type: boolean
          description: default acl status
        case_sensitive:
          type: boolean
          description: case sensitive
        recycled:
          type: boolean
          description: recycle status
      title: FSSMBShareUpdateReq_Share
    FSSMBSharesResp:
      type: object
      required:
      - fs_smb_shares
      properties:
        fs_smb_shares:
          type: array
          description: fs smb shares
          items:
            $ref: '#/components/schemas/FSSMBShare'
      title: FSSMBSharesResp
      example:
        fs_smb_shares:
        - acl_inherited: true
          fs_quota_tree:
            name: name
            id: 5
          update: '2000-01-23T04:56:07.000+00:00'
          security: security
          recycled: true
          mapping_num: 1
          case_sensitive: true
          fs_folder:
            name: name
            id: 6
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          acl_num: 0
          id: 6
          fs_gateway_group:
            name: name
            id: 6
            vip_mask: 1
            vip: vip
          action_status: action_status
          status: status
        - acl_inherited: true
          fs_quota_tree:
            name: name
            id: 5
          update: '2000-01-23T04:56:07.000+00:00'
          security: security
          recycled: true
          mapping_num: 1
          case_sensitive: true
          fs_folder:
            name: name
            id: 6
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          acl_num: 0
          id: 6
          fs_gateway_group:
            name: name
            id: 6
            vip_mask: 1
            vip: vip
          action_status: action_status
          status: status
    FSSMBShareUpdateReq:
      type: object
      required:
      - fs_smb_share
      properties:
        fs_smb_share:
          $ref: '#/components/schemas/FSSMBShareUpdateReq_Share'
      title: FSSMBShareUpdateReq
    FSSMBShareAddACLsReq:
      type: object
      required:
      - fs_smb_share
      properties:
        fs_smb_share:
          $ref: '#/components/schemas/FSSMBShareAddACLsReq_Share'
      title: FSSMBShareAddACLsReq
    FSSMBShareUpdateACLsReq:
      type: object
      required:
      - fs_smb_share
      properties:
        fs_smb_share:
          $ref: '#/components/schemas/FSSMBShareUpdateACLsReq_Share'
      title: FSSMBShareUpdateACLsReq
    FSSMBShareResp:
      type: object
      required:
      - fs_smb_share
      properties:
        fs_smb_share:
          description: fs smb share
          $ref: '#/components/schemas/FSSMBShare'
      title: FSSMBShareResp
      example:
        fs_smb_share:
          acl_inherited: true
          fs_quota_tree:
            name: name
            id: 5
          update: '2000-01-23T04:56:07.000+00:00'
          security: security
          recycled: true
          mapping_num: 1
          case_sensitive: true
          fs_folder:
            name: name
            id: 6
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          acl_num: 0
          id: 6
          fs_gateway_group:
            name: name
            id: 6
            vip_mask: 1
            vip: vip
          action_status: action_status
          status: status
    FSSMBShare:
      type: object
      properties:
        acl_inherited:
          type: boolean
        acl_num:
          type: integer
          format: int64
        action_status:
          type: string
        case_sensitive:
          type: boolean
        create:
          type: string
          format: date-time
        fs_folder:
          $ref: '#/components/schemas/FSFolder_Nestview'
        fs_gateway_group:
          $ref: '#/components/schemas/FSGatewayGroup_Nestview'
        fs_quota_tree:
          $ref: '#/components/schemas/FSQuotaTree_Nestview'
        id:
          type: integer
          format: int64
        mapping_num:
          type: integer
          format: int64
        name:
          type: string
        recycled:
          type: boolean
        security:
          type: string
        status:
          type: string
        update:
          type: string
          format: date-time
      title: FSSMBShare
      description: FSSMBShare defines model of fs smb share
      example:
        acl_inherited: true
        fs_quota_tree:
          name: name
          id: 5
        update: '2000-01-23T04:56:07.000+00:00'
        security: security
        recycled: true
        mapping_num: 1
        case_sensitive: true
        fs_folder:
          name: name
          id: 6
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        acl_num: 0
        id: 6
        fs_gateway_group:
          name: name
          id: 6
          vip_mask: 1
          vip: vip
        action_status: action_status
        status: status
    FSQuotaTree_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: FSQuotaTree_Nestview
      example:
        name: name
        id: 5
    FSSMBShareCreateReq:
      type: object
      required:
      - fs_smb_share
      properties:
        fs_smb_share:
          $ref: '#/components/schemas/FSSMBShareCreateReq_Share'
      title: FSSMBShareCreateReq
    FSSMBShareRemoveACLsReq_Share:
      type: object
      required:
      - fs_smb_share_acl_ids
      properties:
        fs_smb_share_acl_ids:
          type: array
          description: access control array
          items:
            type: integer
            format: int64
      title: FSSMBShareRemoveACLsReq_Share
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
