openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Os Samples API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: os-samples
  description: OSSampleController API /os-samples
paths:
  /os-samples/:
    get:
      tags:
      - os-samples
      description: Get os samples
      operationId: GetOSSamples
      parameters:
      - name: time
        in: query
        description: query time(url encode RFC3339)
        required: false
        x-exportParamName: Time
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSSampleResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get OS samples
      x-summary-source: derived
  /os-samples/{user_name}:
    get:
      tags:
      - os-samples
      description: Get os samples by user name
      operationId: GetOSSamplesByUserName
      parameters:
      - name: user_name
        in: path
        description: os user name
        required: true
        x-exportParamName: UserName
        schema:
          type: string
      - name: time
        in: query
        description: query time(url encode RFC3339)
        required: false
        x-exportParamName: Time
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSSampleResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get OS samples by user name
      x-summary-source: derived
  /os-samples/{user_name}/{bucket_name}:
    get:
      tags:
      - os-samples
      description: get os samples by os bucket name
      operationId: GetOSSamplesByBucketName
      parameters:
      - name: user_name
        in: path
        description: os user name
        required: true
        x-exportParamName: UserName
        schema:
          type: string
          default: 'true'
      - name: bucket_name
        in: path
        description: os bucket name
        required: true
        x-exportParamName: BucketName
        schema:
          type: string
          default: 'true'
      - name: time
        in: query
        description: query time(url encode RFC3339)
        required: false
        x-exportParamName: Time
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSSampleResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get OS samples by bucket name
      x-summary-source: derived
components:
  schemas:
    OSSampleResp:
      type: object
      properties:
        os_samples:
          type: array
          items:
            type: object
            additionalProperties:
              type: array
              items:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/OSSample'
      title: OSSampleResp
      example:
        os_samples:
        - key:
          - key:
              used_capacity_bytes:
                key: 5
              post_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              objects: 5
              delete_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              get_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              put_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              list_bucket_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
          - key:
              used_capacity_bytes:
                key: 5
              post_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              objects: 5
              delete_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              get_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              put_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              list_bucket_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
        - key:
          - key:
              used_capacity_bytes:
                key: 5
              post_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              objects: 5
              delete_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              get_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              put_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              list_bucket_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
          - key:
              used_capacity_bytes:
                key: 5
              post_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              objects: 5
              delete_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              get_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              put_obj_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
              list_bucket_category:
                ops: 6
                download_bytes: 0
                upload_bytes: 1
    OSBucketUsageCategory:
      type: object
      properties:
        download_bytes:
          type: integer
          format: int64
        ops:
          type: integer
          format: int64
        upload_bytes:
          type: integer
          format: int64
      title: OSBucketUsageCategory
      description: OSBucketUsageCategory contain usage info
      example:
        ops: 6
        download_bytes: 0
        upload_bytes: 1
    OSSample:
      type: object
      properties:
        delete_obj_category:
          $ref: '#/components/schemas/OSBucketUsageCategory'
        get_obj_category:
          $ref: '#/components/schemas/OSBucketUsageCategory'
        list_bucket_category:
          $ref: '#/components/schemas/OSBucketUsageCategory'
        objects:
          type: integer
          format: int64
        post_obj_category:
          $ref: '#/components/schemas/OSBucketUsageCategory'
        put_obj_category:
          $ref: '#/components/schemas/OSBucketUsageCategory'
        used_capacity_bytes:
          type: object
          additionalProperties:
            type: integer
            format: int64
      title: OSSample
      description: OSSample contains os samples
      example:
        used_capacity_bytes:
          key: 5
        post_obj_category:
          ops: 6
          download_bytes: 0
          upload_bytes: 1
        objects: 5
        delete_obj_category:
          ops: 6
          download_bytes: 0
          upload_bytes: 1
        get_obj_category:
          ops: 6
          download_bytes: 0
          upload_bytes: 1
        put_obj_category:
          ops: 6
          download_bytes: 0
          upload_bytes: 1
        list_bucket_category:
          ops: 6
          download_bytes: 0
          upload_bytes: 1
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
