openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Version API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: Version
  description: VersionController Operations about Version
paths:
  /version/:
    get:
      tags:
      - Version
      description: show version
      operationId: GetVersion
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResp'
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get version
      x-summary-source: derived
components:
  schemas:
    VersionResp:
      type: object
      required:
      - version
      properties:
        version:
          type: string
          description: version
      title: VersionResp
      example:
        version: version
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
