openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Fs Clients API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: fs-clients
  description: FSClientController provides APIs for file storage client
paths:
  /fs-clients/:
    get:
      tags:
      - fs-clients
      description: List file storage clients
      operationId: ListFSClients
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      - name: fs_client_group_id
        in: query
        description: file storage client group id
        required: false
        x-exportParamName: FsClientGroupId
        schema:
          type: integer
          format: int64
      - name: not_fs_client_group_id
        in: query
        description: group id the client don't belong to
        required: false
        x-exportParamName: NotFsClientGroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSClientsResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List FS clients
      x-summary-source: derived
    post:
      tags:
      - fs-clients
      description: Create file storage client
      operationId: CreateFSClient
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSClientResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSClientCreateReq'
        description: client info
        required: true
      summary: Create FS client
      x-summary-source: derived
  /fs-clients/{fs_client_id}:
    get:
      tags:
      - fs-clients
      description: Get file storage client
      operationId: GetFSClient
      parameters:
      - name: fs_client_id
        in: path
        description: client id
        required: true
        x-exportParamName: FsClientId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSClientResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get FS client
      x-summary-source: derived
    delete:
      tags:
      - fs-clients
      description: delete file storage client
      operationId: DeleteFSClient
      parameters:
      - name: fs_client_id
        in: path
        description: client id
        required: true
        x-exportParamName: FsClientId
        schema:
          type: integer
          format: int64
      responses:
        204:
          description: Not Content
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete FS client
      x-summary-source: derived
    patch:
      tags:
      - fs-clients
      description: Update file storage client
      operationId: UpdateFSClient
      parameters:
      - name: fs_client_id
        in: path
        description: client id
        required: true
        x-exportParamName: FsClientId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSClientResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSClientUpdateReq'
        description: client info
        required: true
      summary: Update FS client
      x-summary-source: derived
components:
  schemas:
    FSClientUpdateReq:
      type: object
      required:
      - fs_client
      properties:
        fs_client:
          $ref: '#/components/schemas/FSClientUpdateReq_Client'
      title: FSClientUpdateReq
    FSClientCreateReq:
      type: object
      required:
      - fs_client
      properties:
        fs_client:
          $ref: '#/components/schemas/FSClientCreateReq_Client'
      title: FSClientCreateReq
    FSClientUpdateReq_Client:
      type: object
      required:
      - name
      properties:
        name:
          type: string
          description: name of client
      title: FSClientUpdateReq_Client
    FSClientCreateReq_Client:
      type: object
      required:
      - ip
      - name
      properties:
        ip:
          type: string
          description: ip of client
        name:
          type: string
          description: name of client
      title: FSClientCreateReq_Client
    FSClientGroup_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: FSClientGroup_Nestview
      example:
        name: name
        id: 6
    FSClient:
      type: object
      properties:
        create:
          type: string
          format: date-time
        fs_client_group_num:
          type: integer
          format: int64
        fs_client_groups:
          type: array
          items:
            $ref: '#/components/schemas/FSClientGroup_Nestview'
        id:
          type: integer
          format: int64
        ip:
          type: string
        name:
          type: string
        update:
          type: string
          format: date-time
      title: FSClient
      description: FSClient defines model of file storage client
      example:
        ip: ip
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        fs_client_groups:
        - name: name
          id: 6
        - name: name
          id: 6
        update: '2000-01-23T04:56:07.000+00:00'
        fs_client_group_num: 0
        id: 1
    FSClientResp:
      type: object
      required:
      - fs_client
      properties:
        fs_client:
          description: file storage client
          $ref: '#/components/schemas/FSClient'
      title: FSClientResp
      example:
        fs_client:
          ip: ip
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          fs_client_groups:
          - name: name
            id: 6
          - name: name
            id: 6
          update: '2000-01-23T04:56:07.000+00:00'
          fs_client_group_num: 0
          id: 1
    FSClientsResp:
      type: object
      required:
      - fs_clients
      properties:
        fs_clients:
          type: array
          description: file storage clients
          items:
            $ref: '#/components/schemas/FSClient'
      title: FSClientsResp
      example:
        fs_clients:
        - ip: ip
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          fs_client_groups:
          - name: name
            id: 6
          - name: name
            id: 6
          update: '2000-01-23T04:56:07.000+00:00'
          fs_client_group_num: 0
          id: 1
        - ip: ip
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          fs_client_groups:
          - name: name
            id: 6
          - name: name
            id: 6
          update: '2000-01-23T04:56:07.000+00:00'
          fs_client_group_num: 0
          id: 1
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
