openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Fs Client Groups API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: fs-client-groups
  description: FSClientGroupController provides APIs for file storage client group
paths:
  /fs-client-groups/:
    get:
      tags:
      - fs-client-groups
      description: List file storage client groups
      operationId: ListFSClientGroups
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      - name: fs_client_id
        in: query
        description: file storage client id
        required: false
        x-exportParamName: FsClientId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSClientGroupsResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List FS client groups
      x-summary-source: derived
    post:
      tags:
      - fs-client-groups
      description: Create file storage client group
      operationId: CreateFSClientGroup
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSClientGroupResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSClientGroupCreateReq'
        description: client group info
        required: true
      summary: Create FS client group
      x-summary-source: derived
  /fs-client-groups/{fs_client_group_id}:
    get:
      tags:
      - fs-client-groups
      description: Get file storage client group
      operationId: GetFSClientGroup
      parameters:
      - name: fs_client_group_id
        in: path
        description: client group id
        required: true
        x-exportParamName: FsClientGroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSClientGroupResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get FS client group
      x-summary-source: derived
    delete:
      tags:
      - fs-client-groups
      description: delete file storage client group
      operationId: DeleteFSClientGroup
      parameters:
      - name: fs_client_group_id
        in: path
        description: client group id
        required: true
        x-exportParamName: FsClientGroupId
        schema:
          type: integer
          format: int64
      responses:
        204:
          description: Not Content
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      summary: Delete FS client group
      x-summary-source: derived
    patch:
      tags:
      - fs-client-groups
      description: Update file storage client group
      operationId: UpdateFSClientGroup
      parameters:
      - name: fs_client_group_id
        in: path
        description: client group id
        required: true
        x-exportParamName: FsClientGroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSClientGroupResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSClientGroupUpdateReq'
        description: client group info
        required: true
      summary: Update FS client group
      x-summary-source: derived
  /fs-client-groups/{fs_client_group_id}/fs-clients:
    put:
      tags:
      - fs-client-groups
      description: add clients to file storage client group
      operationId: AddFSClients
      parameters:
      - name: fs_client_group_id
        in: path
        description: client group id
        required: true
        x-exportParamName: FsClientGroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSClientGroupResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSClientGroupAddClientsReq'
        description: clients info
        required: true
      summary: Add FS clients
      x-summary-source: derived
    delete:
      tags:
      - fs-client-groups
      description: remove clients from file storage client group
      operationId: RemoveFSClients
      parameters:
      - name: fs_client_group_id
        in: path
        description: client group id
        required: true
        x-exportParamName: FsClientGroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSClientGroupResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSClientGroupRemoveClientsReq'
        description: clients info
        required: true
      summary: Remove FS clients
      x-summary-source: derived
components:
  schemas:
    FSClientGroupCreateReq_ClientGroup:
      type: object
      required:
      - fs_client_ids
      - name
      properties:
        fs_client_ids:
          type: array
          description: ids of clients
          items:
            type: integer
            format: int64
        name:
          type: string
          description: name of client group
      title: FSClientGroupCreateReq_ClientGroup
    FSClientGroupUpdateReq_ClientGroup:
      type: object
      required:
      - name
      properties:
        name:
          type: string
          description: name of client group
      title: FSClientGroupUpdateReq_ClientGroup
    FSClientGroupsResp:
      type: object
      required:
      - fs_client_groups
      properties:
        fs_client_groups:
          type: array
          description: file storage client groups
          items:
            $ref: '#/components/schemas/FSClientGroup'
      title: FSClientGroupsResp
      example:
        fs_client_groups:
        - client_num: 0
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          fs_clients:
          - name: name
            id: 6
          - name: name
            id: 6
          id: 1
          action_status: action_status
        - client_num: 0
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          fs_clients:
          - name: name
            id: 6
          - name: name
            id: 6
          id: 1
          action_status: action_status
    FSClientGroupRemoveClientsReq_ClientGroup:
      type: object
      required:
      - fs_client_ids
      properties:
        fs_client_ids:
          type: array
          description: ids of clients
          items:
            type: integer
            format: int64
      title: FSClientGroupRemoveClientsReq_ClientGroup
    FSClientGroupResp:
      type: object
      required:
      - fs_client_group
      properties:
        fs_client_group:
          description: file storage client group
          $ref: '#/components/schemas/FSClientGroup'
      title: FSClientGroupResp
      example:
        fs_client_group:
          client_num: 0
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          fs_clients:
          - name: name
            id: 6
          - name: name
            id: 6
          id: 1
          action_status: action_status
    FSClientGroupAddClientsReq:
      type: object
      required:
      - fs_client_group
      properties:
        fs_client_group:
          $ref: '#/components/schemas/FSClientGroupAddClientsReq_ClientGroup'
      title: FSClientGroupAddClientsReq
    FSClient_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: FSClient_Nestview
      example:
        name: name
        id: 6
    FSClientGroupAddClientsReq_ClientGroup:
      type: object
      required:
      - fs_client_ids
      properties:
        fs_client_ids:
          type: array
          description: ids of clients
          items:
            type: integer
            format: int64
      title: FSClientGroupAddClientsReq_ClientGroup
    FSClientGroupUpdateReq:
      type: object
      required:
      - fs_client_group
      properties:
        fs_client_group:
          $ref: '#/components/schemas/FSClientGroupUpdateReq_ClientGroup'
      title: FSClientGroupUpdateReq
    FSClientGroupCreateReq:
      type: object
      required:
      - fs_client_group
      properties:
        fs_client_group:
          $ref: '#/components/schemas/FSClientGroupCreateReq_ClientGroup'
      title: FSClientGroupCreateReq
    FSClientGroup:
      type: object
      properties:
        action_status:
          type: string
        client_num:
          type: integer
          format: int64
        create:
          type: string
          format: date-time
        fs_clients:
          type: array
          items:
            $ref: '#/components/schemas/FSClient_Nestview'
        id:
          type: integer
          format: int64
        name:
          type: string
        update:
          type: string
          format: date-time
      title: FSClientGroup
      description: FSClientGroup defines model of file storage client group
      example:
        client_num: 0
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        fs_clients:
        - name: name
          id: 6
        - name: name
          id: 6
        id: 1
        action_status: action_status
    FSClientGroupRemoveClientsReq:
      type: object
      required:
      - fs_client_group
      properties:
        fs_client_group:
          $ref: '#/components/schemas/FSClientGroupRemoveClientsReq_ClientGroup'
      title: FSClientGroupRemoveClientsReq
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
