openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Host Initializations API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: host-initializations
  description: HostInitializationController provides API for host initialization
paths:
  /host-initializations/:
    post:
      tags:
      - host-initializations
      description: Create host initialization
      operationId: HostInitialization
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostInitializationResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HostInitializationReq'
        description: host initialization info
        required: true
      summary: Host initialization
      x-summary-source: derived
components:
  schemas:
    HostInitializationResp:
      type: object
      properties:
        host_initialization:
          $ref: '#/components/schemas/HostInitialization'
      title: HostInitializationResp
      example:
        host_initialization:
          hostname_prefix: hostname_prefix
          disable_firewalld: true
          set_hostname: true
          create: '2000-01-23T04:56:07.000+00:00'
          id: 0
          message: message
          admin_ips:
          - admin_ips
          - admin_ips
          ssh_user: ssh_user
          status: status
    HostInitialization:
      type: object
      properties:
        admin_ips:
          type: array
          items:
            type: string
        create:
          type: string
          format: date-time
        disable_firewalld:
          type: boolean
        hostname_prefix:
          type: string
        id:
          type: integer
          format: int64
        message:
          type: string
        set_hostname:
          type: boolean
        ssh_user:
          type: string
        status:
          type: string
      title: HostInitialization
      description: HostInitialization is the model of host initialization
      example:
        hostname_prefix: hostname_prefix
        disable_firewalld: true
        set_hostname: true
        create: '2000-01-23T04:56:07.000+00:00'
        id: 0
        message: message
        admin_ips:
        - admin_ips
        - admin_ips
        ssh_user: ssh_user
        status: status
    HostInitializationReq:
      type: object
      properties:
        host_initialization:
          $ref: '#/components/schemas/HostInitializationReq_Initialization'
      title: HostInitializationReq
      example:
        host_initialization:
          hostname_prefix: hostname_prefix
          disable_firewalld: true
          set_hostname: true
          ssh_password: ssh_password
          admin_ips:
          - admin_ips
          - admin_ips
          ssh_user: ssh_user
    HostInitializationReq_Initialization:
      type: object
      required:
      - admin_ips
      - ssh_user
      properties:
        admin_ips:
          type: array
          items:
            type: string
        disable_firewalld:
          type: boolean
        hostname_prefix:
          type: string
        set_hostname:
          type: boolean
        ssh_password:
          type: string
        ssh_user:
          type: string
      title: HostInitializationReq_Initialization
      example:
        hostname_prefix: hostname_prefix
        disable_firewalld: true
        set_hostname: true
        ssh_password: ssh_password
        admin_ips:
        - admin_ips
        - admin_ips
        ssh_user: ssh_user
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
