openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Os Search Engines API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: os-search-engines
  description: OSSearchEngineController provides APIs for OS search engine
paths:
  /os-search-engines/:
    get:
      tags:
      - os-search-engines
      description: List OS search engine
      operationId: ListOSSearchEngines
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSSearchEnginesResp'
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List OS search engines
      x-summary-source: derived
    post:
      tags:
      - os-search-engines
      operationId: CreateOSSearchEngine
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSSearchEngineResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OSSearchEngineCreateReq'
        description: OS search engine info
        required: true
      summary: Create OS search engine
      x-summary-source: derived
  /os-search-engines/{os_search_engine_id}:
    get:
      tags:
      - os-search-engines
      description: Get a OS search engine
      operationId: GetOSSearchEngine
      parameters:
      - name: os_search_engine_id
        in: path
        description: OS search engine id
        required: true
        x-exportParamName: OsSearchEngineId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSSearchEngineResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get OS search engine
      x-summary-source: derived
    delete:
      tags:
      - os-search-engines
      description: delete OS search engine
      operationId: DeleteOSSearchEngine
      parameters:
      - name: os_search_engine_id
        in: path
        description: OS search engine id
        required: true
        x-exportParamName: OsSearchEngineId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSSearchEngineResp'
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete OS search engine
      x-summary-source: derived
    patch:
      tags:
      - os-search-engines
      description: change OS search engine falvor or data size
      operationId: ChangeOSSearchEngine
      parameters:
      - name: os_search_engine_id
        in: path
        description: OS search engine id
        required: true
        x-exportParamName: OsSearchEngineId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSSearchEngineResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OSSearchEngineUpdateReq'
        description: os search gateways info
        required: true
      summary: Change OS search engine
      x-summary-source: derived
  /os-search-engines/{os_search_engine_id}/samples:
    get:
      tags:
      - os-search-engines
      description: get an object storage search engine's samples
      operationId: GetOSSearchEngineSamples
      parameters:
      - name: os_search_engine_id
        in: path
        description: OS search engine id
        required: true
        x-exportParamName: OsSearchEngineId
        schema:
          type: integer
          format: int64
      - name: duration_begin
        in: query
        description: duration begin timestamp
        required: false
        x-exportParamName: DurationBegin
        schema:
          type: string
      - name: duration_end
        in: query
        description: duration end timestamp
        required: false
        x-exportParamName: DurationEnd
        schema:
          type: string
      - name: period
        in: query
        description: samples period
        required: false
        x-exportParamName: Period
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSSearchEngineSamplesResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get OS search engine samples
      x-summary-source: derived
  /os-search-engines/{os_search_engine_id}:add-os-search-gateways:
    post:
      tags:
      - os-search-engines
      description: Create new OS Search gateways on OS search engine
      operationId: AddOSSearchGateways
      parameters:
      - name: os_search_engine_id
        in: path
        description: OS search engine id
        required: true
        x-exportParamName: OsSearchEngineId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSSearchEngineResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OSSearchEngineAddGatewaysReq'
        description: os search gateways info
        required: true
      summary: Add OS search gateways
      x-summary-source: derived
  /os-search-engines/{os_search_engine_id}:remove-os-search-gateways:
    post:
      tags:
      - os-search-engines
      description: remove OS search gateways from OS search engine
      operationId: RemoveOSSearchGateways
      parameters:
      - name: os_search_engine_id
        in: path
        description: OS search engine id
        required: true
        x-exportParamName: OsSearchEngineId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSSearchEngineResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OSSearchEngineRemoveGatewaysReq'
        description: os search gateways info
        required: true
      summary: Remove OS search gateways
      x-summary-source: derived
  /os-search-engines/{os_search_engine_id}:start:
    post:
      tags:
      - os-search-engines
      description: start OS search gateways from OS search engine
      operationId: StartOSSearchEngine
      parameters:
      - name: os_search_engine_id
        in: path
        description: OS search engine id
        required: true
        x-exportParamName: OsSearchEngineId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSSearchEngineResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Start OS search engine
      x-summary-source: derived
  /os-search-engines/{os_search_engine_id}:stop:
    post:
      tags:
      - os-search-engines
      description: stop OS search gateways from OS search engine
      operationId: StopOSSearchEngine
      parameters:
      - name: os_search_engine_id
        in: path
        description: OS search engine id
        required: true
        x-exportParamName: OsSearchEngineId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSSearchEngineResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Stop OS search engine
      x-summary-source: derived
components:
  schemas:
    OSSearchEngine:
      type: object
      properties:
        action_status:
          type: string
        allocated_size:
          type: integer
          format: int64
        create:
          type: string
          format: date-time
        gateway_data_size:
          type: integer
          format: int64
        gateway_flavor:
          $ref: '#/components/schemas/VMFlavor_Nestview'
        gateway_http_port:
          type: integer
          format: int64
        gateway_transport_port:
          type: integer
          format: int64
        id:
          type: integer
          format: int64
        search_s3_load_balancer_group:
          $ref: '#/components/schemas/S3LoadBalancerGroup_Nestview'
        size:
          type: integer
          format: int64
        status:
          type: string
        sync_s3_load_balancer_group:
          $ref: '#/components/schemas/S3LoadBalancerGroup_Nestview'
        update:
          type: string
          format: date-time
      title: OSSearchEngine
      description: 'OSSearchEngine defines model of OS search engine TODO(penghui): Load balancer

        group'
    OSSearchGatewayReq:
      type: object
      required:
      - host_id
      - pool_id
      properties:
        host_id:
          type: integer
          format: int64
          description: host id
        pool_id:
          type: integer
          format: int64
      title: OSSearchGatewayReq
    S3LoadBalancerGroup_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        status:
          type: string
      title: S3LoadBalancerGroup_Nestview
      example:
        name: name
        id: 6
        status: status
    OSSearchEngineRecord:
      title: OSSearchEngineRecord
      allOf:
      - $ref: '#/components/schemas/OSSearchEngine'
      - properties:
          samples:
            type: array
            items:
              $ref: '#/components/schemas/OSSearchEngineStat'
      description: OSSearchEngineRecord is used to combine OSSearchEngine and OSSearchEngineStat
    VMFlavor_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: VMFlavor_Nestview
    OSSearchEngineStat:
      type: object
      properties:
        average_meta_query_latency:
          type: number
          format: double
        create:
          type: string
          format: date-time
        meta_query_pm:
          type: number
          format: double
        sync_bandwidth_kbyte:
          type: number
          format: double
        sync_objects_pm:
          type: number
          format: double
        total_meta_num:
          type: integer
          format: int64
        total_meta_size_bytes:
          type: integer
          format: int64
      title: OSSearchEngineStat
      description: OSSearchEngineStat contains info of os search engine
      example:
        average_meta_query_latency: 0.8008281904610115
        total_meta_num: 5
        total_meta_size_bytes: 2
        create: '2000-01-23T04:56:07.000+00:00'
        sync_objects_pm: 5.962133916683182
        meta_query_pm: 6.027456183070403
        sync_bandwidth_kbyte: 1.4658129805029452
    OSSearchEngineCreateReq_SearchEngine:
      type: object
      required:
      - gateway_data_size
      - gateway_flavor_id
      - os_search_gateways
      properties:
        gateway_data_size:
          type: integer
          format: int64
        gateway_flavor_id:
          type: integer
          format: int64
        gateway_http_port:
          type: integer
          format: int64
        gateway_transport_port:
          type: integer
          format: int64
        os_search_gateways:
          type: array
          items:
            $ref: '#/components/schemas/OSSearchGatewayReq'
      title: OSSearchEngineCreateReq_SearchEngine
    OSSearchEngineAddGatewaysReq:
      type: object
      required:
      - os_search_engine
      properties:
        os_search_engine:
          $ref: '#/components/schemas/OSSearchEngineAddGatewaysReq_SearchEngine'
      title: OSSearchEngineAddGatewaysReq
    OSSearchEngineAddGatewaysReq_SearchEngine:
      type: object
      required:
      - os_search_gateways
      properties:
        os_search_gateways:
          type: array
          items:
            $ref: '#/components/schemas/OSSearchGatewayReq'
      title: OSSearchEngineAddGatewaysReq_SearchEngine
    OSSearchEngineSamplesResp:
      type: object
      required:
      - os_search_engine_samples
      properties:
        os_search_engine_samples:
          type: array
          description: os search engine samples
          items:
            $ref: '#/components/schemas/OSSearchEngineStat'
      title: OSSearchEngineSamplesResp
      example:
        os_search_engine_samples:
        - average_meta_query_latency: 0.8008281904610115
          total_meta_num: 5
          total_meta_size_bytes: 2
          create: '2000-01-23T04:56:07.000+00:00'
          sync_objects_pm: 5.962133916683182
          meta_query_pm: 6.027456183070403
          sync_bandwidth_kbyte: 1.4658129805029452
        - average_meta_query_latency: 0.8008281904610115
          total_meta_num: 5
          total_meta_size_bytes: 2
          create: '2000-01-23T04:56:07.000+00:00'
          sync_objects_pm: 5.962133916683182
          meta_query_pm: 6.027456183070403
          sync_bandwidth_kbyte: 1.4658129805029452
    OSSearchEnginesResp:
      type: object
      required:
      - os_search_engines
      properties:
        os_search_engines:
          type: array
          description: object storage search engine
          items:
            $ref: '#/components/schemas/OSSearchEngineRecord'
      title: OSSearchEnginesResp
      example:
        os_search_engines:
        - ''
        - ''
    OSSearchEngineCreateReq:
      type: object
      required:
      - os_search_engine
      properties:
        os_search_engine:
          $ref: '#/components/schemas/OSSearchEngineCreateReq_SearchEngine'
      title: OSSearchEngineCreateReq
    OSSearchEngineResp:
      type: object
      required:
      - os_search_engine
      properties:
        os_search_engine:
          description: object storage search engine
          $ref: '#/components/schemas/OSSearchEngineRecord'
      title: OSSearchEngineResp
      example:
        os_search_engine: ''
    OSSearchEngineRemoveGatewaysReq_SearchEngine:
      type: object
      required:
      - os_search_gateway_ids
      properties:
        os_search_gateway_ids:
          type: array
          items:
            type: integer
            format: int64
      title: OSSearchEngineRemoveGatewaysReq_SearchEngine
    OSSearchEngineUpdateReq_SearchEngine:
      type: object
      properties:
        gateway_data_size:
          type: integer
          format: int64
        gateway_flavor_id:
          type: integer
          format: int64
      title: OSSearchEngineUpdateReq_SearchEngine
    OSSearchEngineUpdateReq:
      type: object
      required:
      - os_search_engine
      properties:
        os_search_engine:
          $ref: '#/components/schemas/OSSearchEngineUpdateReq_SearchEngine'
      title: OSSearchEngineUpdateReq
    OSSearchEngineRemoveGatewaysReq:
      type: object
      required:
      - os_search_engine
      properties:
        os_search_engine:
          $ref: '#/components/schemas/OSSearchEngineRemoveGatewaysReq_SearchEngine'
      title: OSSearchEngineRemoveGatewaysReq
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
