openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Vip Groups API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: vip-groups
  description: VIPGroupController API /vip-groups
paths:
  /vip-groups/:
    get:
      tags:
      - vip-groups
      description: List vip groups
      operationId: ListVIPGroups
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: resource_type
        in: query
        description: resource type
        required: false
        x-exportParamName: ResourceType
        schema:
          type: string
      - name: resource_id
        in: query
        description: resource id
        required: false
        x-exportParamName: ResourceId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VIPGroupResps'
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List VIP groups
      x-summary-source: derived
    post:
      tags:
      - vip-groups
      description: Create a vip group
      operationId: CreateVIPGroup
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VIPGroupResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VIPGroupCreateReq'
        description: vip group info
        required: true
      summary: Create VIP group
      x-summary-source: derived
  /vip-groups/{vip_group_id}:
    get:
      tags:
      - vip-groups
      description: Get a vip group
      operationId: GetVIPGroup
      parameters:
      - name: vip_group_id
        in: path
        description: vip group id
        required: true
        x-exportParamName: VipGroupId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VIPGroupResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get VIP group
      x-summary-source: derived
    delete:
      tags:
      - vip-groups
      description: Delete a vip group
      operationId: DeleteVIPGroup
      parameters:
      - name: vip_group_id
        in: path
        description: vip group id
        required: true
        x-exportParamName: VipGroupId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VIPGroupResp'
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete VIP group
      x-summary-source: derived
    patch:
      tags:
      - vip-groups
      description: Update a vip group
      operationId: UpdateVIPGroup
      parameters:
      - name: vip_group_id
        in: path
        description: vip group id
        required: true
        x-exportParamName: VipGroupId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VIPGroupResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VIPGroupUpdateReq'
        description: vip group info
        required: true
      summary: Update VIP group
      x-summary-source: derived
  /vip-groups/{vip_group_id}:redeploy:
    post:
      tags:
      - vip-groups
      description: Redeploy a vip group
      operationId: RedeployVIPGroup
      parameters:
      - name: vip_group_id
        in: path
        description: vip group id
        required: true
        x-exportParamName: VipGroupId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VIPGroupResp'
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Redeploy VIP group
      x-summary-source: derived
components:
  schemas:
    VIPGroupResp:
      type: object
      required:
      - vip_group
      properties:
        vip_group:
          $ref: '#/components/schemas/VIPGroup'
      title: VIPGroupResp
      example:
        vip_group:
          name: name
          resource_type: resource_type
          create: '2000-01-23T04:56:07.000+00:00'
          resource_id: 6
          update: '2000-01-23T04:56:07.000+00:00'
          id: 0
          preempt: true
          action_status: action_status
          network: network
          status: status
    VIPGroupUpdateReq_VIPGroup:
      type: object
      properties:
        preempt:
          type: boolean
      title: VIPGroupUpdateReq_VIPGroup
    VIPGroupCreateReq_VIPGroup_VIPs_Elt:
      type: object
      required:
      - ip
      - network_address_id
      properties:
        ip:
          type: string
        mask:
          type: integer
          format: int64
        network_address_id:
          type: integer
          format: int64
      title: VIPGroupCreateReq_VIPGroup_VIPs_Elt
    VIPGroupCreateReq:
      type: object
      required:
      - vip_group
      properties:
        vip_group:
          $ref: '#/components/schemas/VIPGroupCreateReq_VIPGroup'
      title: VIPGroupCreateReq
    VIPGroupCreateReq_VIPGroup:
      type: object
      required:
      - network
      - resource_id
      - resource_type
      - vips
      properties:
        network:
          type: string
        preempt:
          type: boolean
        resource_id:
          type: integer
          format: int64
        resource_type:
          type: string
        vips:
          type: array
          items:
            $ref: '#/components/schemas/VIPGroupCreateReq_VIPGroup_VIPs_Elt'
      title: VIPGroupCreateReq_VIPGroup
    VIPGroup:
      type: object
      properties:
        action_status:
          type: string
        create:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        name:
          type: string
        network:
          type: string
        preempt:
          type: boolean
        resource_id:
          type: integer
          format: int64
        resource_type:
          type: string
        status:
          type: string
        update:
          type: string
          format: date-time
      title: VIPGroup
      description: VIPGroup contains many vips and associated to a resource.
      example:
        name: name
        resource_type: resource_type
        create: '2000-01-23T04:56:07.000+00:00'
        resource_id: 6
        update: '2000-01-23T04:56:07.000+00:00'
        id: 0
        preempt: true
        action_status: action_status
        network: network
        status: status
    VIPGroupResps:
      type: object
      required:
      - vip_groups
      properties:
        vip_groups:
          type: array
          items:
            $ref: '#/components/schemas/VIPGroup'
      title: VIPGroupResps
      example:
        vip_groups:
        - name: name
          resource_type: resource_type
          create: '2000-01-23T04:56:07.000+00:00'
          resource_id: 6
          update: '2000-01-23T04:56:07.000+00:00'
          id: 0
          preempt: true
          action_status: action_status
          network: network
          status: status
        - name: name
          resource_type: resource_type
          create: '2000-01-23T04:56:07.000+00:00'
          resource_id: 6
          update: '2000-01-23T04:56:07.000+00:00'
          id: 0
          preempt: true
          action_status: action_status
          network: network
          status: status
    VIPGroupUpdateReq:
      type: object
      required:
      - vip_group
      properties:
        vip_group:
          $ref: '#/components/schemas/VIPGroupUpdateReq_VIPGroup'
      title: VIPGroupUpdateReq
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
