openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Os Custom Labels API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: os-custom-labels
  description: OSCustomLabelController provides API for object storage custom label
paths:
  /os-custom-labels/:
    get:
      tags:
      - os-custom-labels
      description: List object storage custom labels
      operationId: ListOSCustomLabels
      parameters:
      - name: bucket_id
        in: query
        description: bucket id
        required: false
        x-exportParamName: BucketId
        schema:
          type: integer
          format: int64
      - name: category
        in: query
        description: 'label category: meta, default, tagging'
        required: false
        x-exportParamName: Category
        schema:
          type: string
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSCustomLabelsResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List OS custom labels
      x-summary-source: derived
  /os-custom-labels/{os_custom_label_id}:
    get:
      tags:
      - os-custom-labels
      description: Get object storage custom label
      operationId: GetOSCustomLabel
      parameters:
      - name: os_custom_label_id
        in: path
        description: os custom label id
        required: true
        x-exportParamName: OsCustomLabelId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSCustomLabelResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      summary: Get OS custom label
      x-summary-source: derived
components:
  schemas:
    ObjectStorageBucket_Nestview_lifecycle:
      properties:
        id:
          type: integer
          format: int64
        rules:
          type: array
          items:
            type: object
            properties: {}
        status:
          type: string
      example:
        rules:
        - '{}'
        - '{}'
        id: 6
        status: status
    OSCustomLabelResp:
      type: object
      required:
      - os_custom_label
      properties:
        os_custom_label:
          description: object storage custom label
          $ref: '#/components/schemas/OSCustomLabel'
      title: OSCustomLabelResp
      example:
        os_custom_label:
          bucket:
            lifecycle:
              rules:
              - '{}'
              - '{}'
              id: 6
              status: status
            name: name
            id: 0
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 0
          category: category
          type: type
          status: status
    OSCustomLabel:
      type: object
      properties:
        bucket:
          $ref: '#/components/schemas/ObjectStorageBucket_Nestview'
        category:
          type: string
        create:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        name:
          type: string
        status:
          type: string
        type:
          type: string
        update:
          type: string
          format: date-time
      title: OSCustomLabel
      description: OSCustomLabel the struct of object storage custom label
      example:
        bucket:
          lifecycle:
            rules:
            - '{}'
            - '{}'
            id: 6
            status: status
          name: name
          id: 0
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        id: 0
        category: category
        type: type
        status: status
    OSCustomLabelsResp:
      type: object
      required:
      - os_custom_labels
      properties:
        os_custom_labels:
          type: array
          description: object storage custom labels
          items:
            $ref: '#/components/schemas/OSCustomLabel'
      title: OSCustomLabelsResp
      example:
        os_custom_labels:
        - bucket:
            lifecycle:
              rules:
              - '{}'
              - '{}'
              id: 6
              status: status
            name: name
            id: 0
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 0
          category: category
          type: type
          status: status
        - bucket:
            lifecycle:
              rules:
              - '{}'
              - '{}'
              id: 6
              status: status
            name: name
            id: 0
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 0
          category: category
          type: type
          status: status
    ObjectStorageBucket_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        lifecycle:
          $ref: '#/components/schemas/ObjectStorageBucket_Nestview_lifecycle'
        name:
          type: string
      title: ObjectStorageBucket_Nestview
      example:
        lifecycle:
          rules:
          - '{}'
          - '{}'
          id: 6
          status: status
        name: name
        id: 0
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
