swagger: '2.0'
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS access-paths fs-smb-sessions API
  contact: {}
  license:
    name: Commercial
basePath: /v1
tags:
- name: fs-smb-sessions
  description: 'FSSMBSessionController provides API for fs SMB session

    '
paths:
  /fs-smb-sessions/:
    get:
      tags:
      - fs-smb-sessions
      description: List fs smb sessions
      operationId: ListFSSMBSessions
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        type: integer
        format: int64
        x-exportParamName: Limit
      - name: offset
        in: query
        description: paging param
        required: false
        type: integer
        format: int64
        x-exportParamName: Offset
      - name: fs_smb_share_id
        in: query
        description: fs smb id
        required: false
        type: integer
        format: int64
        x-exportParamName: FsSmbShareId
      - name: q
        in: query
        description: query param of search
        required: false
        type: string
        x-exportParamName: Q
      - name: sort
        in: query
        description: sort param of search
        required: false
        type: string
        x-exportParamName: Sort
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/FSSMBSessionsResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
definitions:
  FSSMBShare_Nestview:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    title: FSSMBShare_Nestview
    example:
      name: name
      id: 6
  FSSMBSession:
    type: object
    properties:
      client_ip:
        type: string
      client_port:
        type: integer
        format: int64
      connected_at:
        type: string
        format: date-time
      create:
        type: string
        format: date-time
      fs_smb_share:
        $ref: '#/definitions/FSSMBShare_Nestview'
      group:
        type: string
      id:
        type: integer
        format: int64
      protocol_version:
        type: string
      update:
        type: string
        format: date-time
      username:
        type: string
    title: FSSMBSession
    description: FSSMBSession defines model of FS SMB session
    example:
      client_port: 0
      fs_smb_share:
        name: name
        id: 6
      protocol_version: protocol_version
      create: '2000-01-23T04:56:07.000+00:00'
      update: '2000-01-23T04:56:07.000+00:00'
      client_ip: client_ip
      connected_at: '2000-01-23T04:56:07.000+00:00'
      id: 1
      group: group
      username: username
  FSSMBSessionsResp:
    type: object
    required:
    - fs_smb_sessions
    properties:
      fs_smb_sessions:
        type: array
        description: fs smb sessions
        items:
          $ref: '#/definitions/FSSMBSession'
    title: FSSMBSessionsResp
    example:
      fs_smb_sessions:
      - client_port: 0
        fs_smb_share:
          name: name
          id: 6
        protocol_version: protocol_version
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        client_ip: client_ip
        connected_at: '2000-01-23T04:56:07.000+00:00'
        id: 1
        group: group
        username: username
      - client_port: 0
        fs_smb_share:
          name: name
          id: 6
        protocol_version: protocol_version
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        client_ip: client_ip
        connected_at: '2000-01-23T04:56:07.000+00:00'
        id: 1
        group: group
        username: username
securityDefinitions:
  tokenInHeader:
    description: auth by token
    type: apiKey
    name: Xms-Auth-Token
    in: header
  tokenInQuery:
    description: auth by token
    type: apiKey
    name: token
    in: query
