openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Trashes API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: trashes
  description: TrashController Operations about Trash
paths:
  /trashes/:
    get:
      tags:
      - trashes
      operationId: ListTrashes
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: type
        in: query
        description: the type of trash
        required: false
        x-exportParamName: Type_
        schema:
          type: string
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrashesResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List trashes
      x-summary-source: derived
  /trashes/{trash_id}:
    get:
      tags:
      - trashes
      description: get a trash
      operationId: GetTrash
      parameters:
      - name: trash_id
        in: path
        description: trash id
        required: true
        x-exportParamName: TrashId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrashResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get trash
      x-summary-source: derived
    patch:
      tags:
      - trashes
      description: Update trash info
      operationId: UpdateTrash
      parameters:
      - name: trash_id
        in: path
        description: trash id
        required: true
        x-exportParamName: TrashId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrashResp'
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrashResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrashUpdateReq'
        description: trash info
        required: true
      summary: Update trash
      x-summary-source: derived
  /trashes/{trash_id}:cleanup:
    post:
      tags:
      - trashes
      operationId: CleanupTrash
      parameters:
      - name: trash_id
        in: path
        description: trash id
        required: true
        x-exportParamName: TrashId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrashResp'
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrashResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Cleanup trash
      x-summary-source: derived
components:
  schemas:
    TrashesResp:
      type: object
      required:
      - trashes
      properties:
        trashes:
          type: array
          description: trashes
          items:
            $ref: '#/components/schemas/Trash'
      title: TrashesResp
      example:
        trashes:
        - trash_resource_num: 6
          resource_type: resource_type
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 0
          enabled: true
          retention: retention
          status: status
        - trash_resource_num: 6
          resource_type: resource_type
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 0
          enabled: true
          retention: retention
          status: status
    Trash:
      type: object
      properties:
        create:
          type: string
          format: date-time
        enabled:
          type: boolean
        id:
          type: integer
          format: int64
        resource_type:
          type: string
        retention:
          type: string
        status:
          type: string
        trash_resource_num:
          type: integer
          format: int64
        update:
          type: string
          format: date-time
      title: Trash
      description: Trash defines the trash attributes.
      example:
        trash_resource_num: 6
        resource_type: resource_type
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        id: 0
        enabled: true
        retention: retention
        status: status
    TrashResp:
      type: object
      required:
      - trash
      properties:
        trash:
          description: trash
          $ref: '#/components/schemas/Trash'
      title: TrashResp
      example:
        trash:
          trash_resource_num: 6
          resource_type: resource_type
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 0
          enabled: true
          retention: retention
          status: status
    TrashUpdateReq_Trash:
      type: object
      properties:
        enabled:
          type: boolean
        retention:
          type: string
      title: TrashUpdateReq_Trash
      example:
        enabled: true
        retention: retention
    TrashUpdateReq:
      type: object
      required:
      - trash
      properties:
        trash:
          $ref: '#/components/schemas/TrashUpdateReq_Trash'
      title: TrashUpdateReq
      example:
        trash:
          enabled: true
          retention: retention
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
