openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Os Policies API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: os-policies
  description: ObjectStoragePolicyController provides API for object storage policy
paths:
  /os-policies/:
    get:
      tags:
      - os-policies
      description: List object storage policies
      operationId: ListPolicies
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectStoragePoliciesResp'
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      summary: List policies
      x-summary-source: derived
    post:
      tags:
      - os-policies
      description: Create object storage policy
      operationId: CreatePolicy
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectStoragePolicyResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectStoragePolicyCreateReq'
        description: policy info
        required: true
      summary: Create policy
      x-summary-source: derived
  /os-policies/{policy_id}:
    get:
      tags:
      - os-policies
      description: Get object storage policy
      operationId: GetPolicy
      parameters:
      - name: policy_id
        in: path
        description: policy id
        required: true
        x-exportParamName: PolicyId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectStoragePolicyResp'
        404:
          description: NotFound
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get policy
      x-summary-source: derived
    delete:
      tags:
      - os-policies
      description: Delete object storage policy
      operationId: DeletePolicy
      parameters:
      - name: policy_id
        in: path
        description: policy id
        required: true
        x-exportParamName: PolicyId
        schema:
          type: integer
          format: int64
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectStoragePolicyResp'
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete policy
      x-summary-source: derived
    patch:
      tags:
      - os-policies
      description: Update object storage policy
      operationId: UpdatePolicy
      parameters:
      - name: policy_id
        in: path
        description: policy id
        required: true
        x-exportParamName: PolicyId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectStoragePolicyResp'
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectStoragePolicyResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectStoragePolicyUpdateReq'
        description: policy info
        required: true
      summary: Update policy
      x-summary-source: derived
components:
  schemas:
    ObjectStoragePolicyCreateReq_Policy:
      type: object
      required:
      - index_pool_id
      - name
      - storage_classes
      properties:
        cache_pool_id:
          type: integer
          format: int64
        compress:
          type: boolean
        crypto:
          type: boolean
        description:
          type: string
        index_pool_id:
          type: integer
          format: int64
        name:
          type: string
        shared:
          type: boolean
        storage_classes:
          type: array
          items:
            $ref: '#/components/schemas/ObjectStoragePolicyCreateReq_Policy_StorageClasses_Elt'
      title: ObjectStoragePolicyCreateReq_Policy
      example:
        shared: true
        storage_classes:
        - active_pool_ids:
          - 1
          - 1
          name: name
          description: description
          class: 5
          inactive_pool_ids:
          - 5
          - 5
        - active_pool_ids:
          - 1
          - 1
          name: name
          description: description
          class: 5
          inactive_pool_ids:
          - 5
          - 5
        cache_pool_id: 0
        compress: true
        name: name
        description: description
        index_pool_id: 6
        crypto: true
    ObjectStoragePolicyUpdateReq_Policy:
      type: object
      properties:
        cache_pool_id:
          type: integer
          format: int64
        compress:
          type: boolean
        crypto:
          type: boolean
        default:
          type: boolean
        description:
          type: string
        shared:
          type: boolean
      title: ObjectStoragePolicyUpdateReq_Policy
      example:
        shared: true
        default: true
        cache_pool_id: 0
        compress: true
        description: description
        crypto: true
    ObjectStoragePolicyResp:
      type: object
      required:
      - os_policy
      properties:
        os_policy:
          description: object storage policy
          $ref: '#/components/schemas/ObjectStoragePolicy'
      title: ObjectStoragePolicyResp
      example:
        os_policy:
          shared: true
          cache_pool:
            name: name
            id: 5
          compress: true
          description: description
          policy_name: policy_name
          update: '2000-01-23T04:56:07.000+00:00'
          bucket_num: 0
          crypto: true
          index_pool:
            name: name
            id: 5
          object_size_threshold: 1
          default: true
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          id: 6
          status: status
    ObjectStoragePolicyCreateReq_Policy_StorageClasses_Elt:
      type: object
      required:
      - active_pool_ids
      - class
      - name
      properties:
        active_pool_ids:
          type: array
          items:
            type: integer
            format: int64
        class:
          type: integer
          format: int32
        description:
          type: string
        inactive_pool_ids:
          type: array
          items:
            type: integer
            format: int64
        name:
          type: string
      title: ObjectStoragePolicyCreateReq_Policy_StorageClasses_Elt
      example:
        active_pool_ids:
        - 1
        - 1
        name: name
        description: description
        class: 5
        inactive_pool_ids:
        - 5
        - 5
    Pool_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: Pool_Nestview
      example:
        name: name
        id: 5
    ObjectStoragePolicyUpdateReq:
      type: object
      properties:
        os_policy:
          $ref: '#/components/schemas/ObjectStoragePolicyUpdateReq_Policy'
      title: ObjectStoragePolicyUpdateReq
      example:
        os_policy:
          shared: true
          default: true
          cache_pool_id: 0
          compress: true
          description: description
          crypto: true
    ObjectStoragePolicy:
      type: object
      properties:
        bucket_num:
          type: integer
          format: int64
        cache_pool:
          $ref: '#/components/schemas/Pool_Nestview'
        compress:
          type: boolean
        create:
          type: string
          format: date-time
        crypto:
          type: boolean
        default:
          type: boolean
        description:
          type: string
        id:
          type: integer
          format: int64
        index_pool:
          $ref: '#/components/schemas/Pool_Nestview'
        name:
          type: string
        object_size_threshold:
          type: integer
          format: int64
        policy_name:
          type: string
        shared:
          type: boolean
        status:
          type: string
        update:
          type: string
          format: date-time
      title: ObjectStoragePolicy
      description: ObjectStoragePolicy is the model of object_storage_policy
      example:
        shared: true
        cache_pool:
          name: name
          id: 5
        compress: true
        description: description
        policy_name: policy_name
        update: '2000-01-23T04:56:07.000+00:00'
        bucket_num: 0
        crypto: true
        index_pool:
          name: name
          id: 5
        object_size_threshold: 1
        default: true
        name: name
        create: '2000-01-23T04:56:07.000+00:00'
        id: 6
        status: status
    ObjectStoragePolicyCreateReq:
      type: object
      properties:
        os_policy:
          $ref: '#/components/schemas/ObjectStoragePolicyCreateReq_Policy'
      title: ObjectStoragePolicyCreateReq
      example:
        os_policy:
          shared: true
          storage_classes:
          - active_pool_ids:
            - 1
            - 1
            name: name
            description: description
            class: 5
            inactive_pool_ids:
            - 5
            - 5
          - active_pool_ids:
            - 1
            - 1
            name: name
            description: description
            class: 5
            inactive_pool_ids:
            - 5
            - 5
          cache_pool_id: 0
          compress: true
          name: name
          description: description
          index_pool_id: 6
          crypto: true
    ObjectStoragePoliciesResp:
      type: object
      required:
      - os_policies
      properties:
        os_policies:
          type: array
          description: object storage policies
          items:
            $ref: '#/components/schemas/ObjectStoragePolicy'
      title: ObjectStoragePoliciesResp
      example:
        os_policies:
        - shared: true
          cache_pool:
            name: name
            id: 5
          compress: true
          description: description
          policy_name: policy_name
          update: '2000-01-23T04:56:07.000+00:00'
          bucket_num: 0
          crypto: true
          index_pool:
            name: name
            id: 5
          object_size_threshold: 1
          default: true
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          id: 6
          status: status
        - shared: true
          cache_pool:
            name: name
            id: 5
          compress: true
          description: description
          policy_name: policy_name
          update: '2000-01-23T04:56:07.000+00:00'
          bucket_num: 0
          crypto: true
          index_pool:
            name: name
            id: 5
          object_size_threshold: 1
          default: true
          name: name
          create: '2000-01-23T04:56:07.000+00:00'
          id: 6
          status: status
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
