openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Targets API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: Targets
  description: TargetController Operations able targets
paths:
  /targets/:
    get:
      tags:
      - Targets
      description: List all targets in the cluster
      operationId: ListTargets
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: host_id
        in: query
        description: host id
        required: false
        x-exportParamName: HostId
        schema:
          type: integer
          format: int64
      - name: access_path_id
        in: query
        description: access path id
        required: false
        x-exportParamName: AccessPathId
        schema:
          type: integer
          format: int64
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TargetsResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List targets
      x-summary-source: derived
    post:
      tags:
      - Targets
      operationId: CreateTarget
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TargetResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TargetCreateReq'
        description: target info
        required: true
      summary: Create target
      x-summary-source: derived
  /targets/{target_id}:
    delete:
      tags:
      - Targets
      description: delete target
      operationId: DeleteTarget
      parameters:
      - name: target_id
        in: path
        description: target id
        required: true
        x-exportParamName: TargetId
        schema:
          type: integer
          format: int64
      - name: force
        in: query
        description: force delete or not
        required: false
        x-exportParamName: Force
        schema:
          type: boolean
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TargetResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete target
      x-summary-source: derived
components:
  schemas:
    TargetCreateReq_Target:
      type: object
      properties:
        access_path_id:
          type: integer
          format: int64
        host_id:
          type: integer
          format: int64
      title: TargetCreateReq_Target
      example:
        access_path_id: 0
        host_id: 6
    TargetResp:
      type: object
      required:
      - target
      properties:
        target:
          $ref: '#/components/schemas/Target'
      title: TargetResp
      example:
        target:
          access_path:
            name: name
            id: 0
          port: 1
          iqn: iqn
          host:
            name: name
            admin_ip: admin_ip
            id: 0
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 6
          board: 0
          status: status
    Target:
      type: object
      properties:
        access_path:
          $ref: '#/components/schemas/AccessPath_Nestview'
        board:
          type: integer
          format: int64
        create:
          type: string
          format: date-time
        host:
          $ref: '#/components/schemas/Host_Nestview'
        id:
          type: integer
          format: int64
        iqn:
          type: string
        port:
          type: integer
          format: int64
        status:
          type: string
        update:
          type: string
          format: date-time
      title: Target
      description: Target defines access path info for host
      example:
        access_path:
          name: name
          id: 0
        port: 1
        iqn: iqn
        host:
          name: name
          admin_ip: admin_ip
          id: 0
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        id: 6
        board: 0
        status: status
    AccessPath_Nestview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      title: AccessPath_Nestview
      example:
        name: name
        id: 0
    TargetCreateReq:
      type: object
      properties:
        target:
          $ref: '#/components/schemas/TargetCreateReq_Target'
      title: TargetCreateReq
      example:
        target:
          access_path_id: 0
          host_id: 6
    Host_Nestview:
      type: object
      required:
      - admin_ip
      properties:
        admin_ip:
          type: string
        id:
          type: integer
          format: int64
        name:
          type: string
      title: Host_Nestview
      example:
        name: name
        admin_ip: admin_ip
        id: 0
    TargetsResp:
      type: object
      required:
      - targets
      properties:
        targets:
          type: array
          items:
            $ref: '#/components/schemas/Target'
      title: TargetsResp
      example:
        targets:
        - access_path:
            name: name
            id: 0
          port: 1
          iqn: iqn
          host:
            name: name
            admin_ip: admin_ip
            id: 0
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 6
          board: 0
          status: status
        - access_path:
            name: name
            id: 0
          port: 1
          iqn: iqn
          host:
            name: name
            admin_ip: admin_ip
            id: 0
          create: '2000-01-23T04:56:07.000+00:00'
          update: '2000-01-23T04:56:07.000+00:00'
          id: 6
          board: 0
          status: status
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
