swagger: '2.0'
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS access-paths fs-nfs-share-acls API
  contact: {}
  license:
    name: Commercial
basePath: /v1
tags:
- name: fs-nfs-share-acls
  description: 'FSNFSShareACLController provides API for fs nfs shares acl

    '
paths:
  /fs-nfs-share-acls/:
    get:
      tags:
      - fs-nfs-share-acls
      description: List fs nfs shares acls
      operationId: ListFSNFSShareACLs
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        type: integer
        format: int64
        x-exportParamName: Limit
      - name: offset
        in: query
        description: paging param
        required: false
        type: integer
        format: int64
        x-exportParamName: Offset
      - name: fs_nfs_share_id
        in: query
        description: fs nfs shares id
        required: false
        type: integer
        format: int64
        x-exportParamName: FsNfsShareId
      - name: q
        in: query
        description: query param of search
        required: false
        type: string
        x-exportParamName: Q
      - name: sort
        in: query
        description: sort param of search
        required: false
        type: string
        x-exportParamName: Sort
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/FSNFSShareACLsResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
definitions:
  FSNFSShare_Nestview:
    type: object
    properties:
      id:
        type: integer
        format: int64
    title: FSNFSShare_Nestview
    example:
      id: 0
  FSNFSShareACLsResp:
    type: object
    required:
    - fs_nfs_share_acls
    properties:
      fs_nfs_share_acls:
        type: array
        description: file storage folder share acls
        items:
          $ref: '#/definitions/FSNFSShareACL'
    title: FSNFSShareACLsResp
    example:
      fs_nfs_share_acls:
      - all_squash: true
        fs_client_group:
          name: name
          id: 6
        fs_client:
          name: name
          id: 6
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        fs_nfs_share:
          id: 0
        permission: permission
        id: 0
        root_squash: true
        type: type
        sync: true
      - all_squash: true
        fs_client_group:
          name: name
          id: 6
        fs_client:
          name: name
          id: 6
        create: '2000-01-23T04:56:07.000+00:00'
        update: '2000-01-23T04:56:07.000+00:00'
        fs_nfs_share:
          id: 0
        permission: permission
        id: 0
        root_squash: true
        type: type
        sync: true
  FSNFSShareACL:
    type: object
    properties:
      all_squash:
        type: boolean
      create:
        type: string
        format: date-time
      fs_client:
        $ref: '#/definitions/FSClient_Nestview'
      fs_client_group:
        $ref: '#/definitions/FSClientGroup_Nestview'
      fs_nfs_share:
        $ref: '#/definitions/FSNFSShare_Nestview'
      id:
        type: integer
        format: int64
      permission:
        type: string
      root_squash:
        type: boolean
      sync:
        type: boolean
      type:
        type: string
      update:
        type: string
        format: date-time
    title: FSNFSShareACL
    description: FSNFSShareACL defines model of fs nfs share ACL
    example:
      all_squash: true
      fs_client_group:
        name: name
        id: 6
      fs_client:
        name: name
        id: 6
      create: '2000-01-23T04:56:07.000+00:00'
      update: '2000-01-23T04:56:07.000+00:00'
      fs_nfs_share:
        id: 0
      permission: permission
      id: 0
      root_squash: true
      type: type
      sync: true
  FSClient_Nestview:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    title: FSClient_Nestview
    example:
      name: name
      id: 6
  FSClientGroup_Nestview:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    title: FSClientGroup_Nestview
    example:
      name: name
      id: 6
securityDefinitions:
  tokenInHeader:
    description: auth by token
    type: apiKey
    name: Xms-Auth-Token
    in: header
  tokenInQuery:
    description: auth by token
    type: apiKey
    name: token
    in: query
