openapi: 3.2.0
info:
  description: XMS is the controller of distributed storage system
  version: SDS_4.2.000.0.200302
  title: XMS Alert Rules API
  contact: {}
  license:
    name: Commercial
servers:
- url: /v1
tags:
- name: Alert Rules
  description: AlertRuleController Operations about alert rule
paths:
  /alert-rules/:
    get:
      tags:
      - Alert Rules
      description: List all alert rules
      operationId: ListAlertRules
      parameters:
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: alert_group_id
        in: query
        description: alert group id
        required: false
        x-exportParamName: AlertGroupId
        schema:
          type: integer
          format: int64
      - name: resource_type
        in: query
        description: resource type of alert rule
        required: false
        x-exportParamName: ResourceType
        schema:
          type: string
      - name: level
        in: query
        description: level of alert rule
        required: false
        x-exportParamName: Level
        schema:
          type: string
      - name: enabled
        in: query
        description: enabled or not
        required: false
        x-exportParamName: Enabled
        schema:
          type: boolean
      - name: q
        in: query
        description: query param of search
        required: false
        x-exportParamName: Q
        schema:
          type: string
      - name: sort
        in: query
        description: sort param of search
        required: false
        x-exportParamName: Sort
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertRulesResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInHeader: []
      - tokenInQuery: []
      summary: List alert rules
      x-summary-source: derived
    post:
      tags:
      - Alert Rules
      description: create alert rule
      operationId: CreateAlertRule
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertRuleResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertRuleCreateReq'
        description: alert rule
        required: true
      summary: Create alert rule
      x-summary-source: derived
    put:
      tags:
      - Alert Rules
      description: create alert rule
      operationId: CreateAlertRule
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertRuleResp'
        400:
          description: BadRequest
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertRuleCreateReq'
        description: alert rule
        required: true
      summary: Create alert rule
      x-summary-source: derived
  /alert-rules/schema:
    get:
      tags:
      - Alert Rules
      description: get alert rule schema
      operationId: GetAlertRuleSchema
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertRuleSchemaResp'
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get alert rule schema
      x-summary-source: derived
  /alert-rules/{rule_id}:
    get:
      tags:
      - Alert Rules
      description: get alert rule
      operationId: GetAlertRule
      parameters:
      - name: rule_id
        in: path
        description: the id of alert rule
        required: true
        x-exportParamName: RuleId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertRuleResp'
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Get alert rule
      x-summary-source: derived
    delete:
      tags:
      - Alert Rules
      description: delete alert rule
      operationId: DeleteAlertRule
      parameters:
      - name: rule_id
        in: path
        description: the id of alert rule
        required: true
        x-exportParamName: RuleId
        schema:
          type: integer
          format: int64
      responses:
        204:
          description: No Content
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: Delete alert rule
      x-summary-source: derived
    patch:
      tags:
      - Alert Rules
      description: set alert rule
      operationId: UpdateAlertRule
      parameters:
      - name: rule_id
        in: path
        description: the id of alert rule
        required: true
        x-exportParamName: RuleId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertRuleResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertRuleUpdateReq'
        description: alert rule
        required: true
      summary: Update alert rule
      x-summary-source: derived
  /alert-rules/{rule_id}/blacklist:
    get:
      tags:
      - Alert Rules
      description: List all blacklist of alert rule
      operationId: ListAlertRuleResourceBlacklist
      parameters:
      - name: rule_id
        in: path
        description: the id of alert rule
        required: true
        x-exportParamName: RuleId
        schema:
          type: integer
          format: int64
      - name: limit
        in: query
        description: paging param
        required: false
        x-exportParamName: Limit
        schema:
          type: integer
          format: int64
      - name: offset
        in: query
        description: paging param
        required: false
        x-exportParamName: Offset
        schema:
          type: integer
          format: int64
      - name: blacklist
        in: query
        description: filter resource in blacklist or not
        required: true
        x-exportParamName: Blacklist
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertRuleResourceBlacklistResp'
        400:
          description: BadRequest
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      summary: List alert rule resource blacklist
      x-summary-source: derived
    post:
      tags:
      - Alert Rules
      description: create resource blacklist of alert rule
      operationId: CreateAlertRuleResourceBlacklist
      parameters:
      - name: rule_id
        in: path
        description: the id of alert rule
        required: true
        x-exportParamName: RuleId
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertRuleResourceBlacklistResp'
        400:
          description: BadRequest
        404:
          description: NotFound
        409:
          description: Conflict
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAlertRuleResourceBlacklistReq'
        description: resource blacklist
        required: true
      summary: Create alert rule resource blacklist
      x-summary-source: derived
    delete:
      tags:
      - Alert Rules
      description: delete resource blacklist of alert rule
      operationId: DeleteAlertRuleResourceBlacklist
      parameters:
      - name: rule_id
        in: path
        description: the id of alert rule
        required: true
        x-exportParamName: RuleId
        schema:
          type: integer
          format: int64
      responses:
        204:
          description: No Content
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: InternalServerError
      security:
      - tokenInQuery: []
      - tokenInHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAlertRuleResourceBlacklistReq'
        description: resource blacklist
        required: true
      summary: Delete alert rule resource blacklist
      x-summary-source: derived
components:
  schemas:
    AlertRuleUpdateReq_Rule:
      type: object
      properties:
        enabled:
          type: boolean
          description: enable the alert rule or not
        trigger_period:
          type: integer
          format: int64
          description: trigger period of alert rule
        trigger_value:
          type: string
          description: trigger value of alert rule
      title: AlertRuleUpdateReq_Rule
      example:
        trigger_period: 0
        trigger_value: trigger_value
        enabled: true
    AlertRulesResp:
      type: object
      required:
      - alert_rules
      properties:
        alert_rules:
          type: array
          description: alert rules
          items:
            $ref: '#/components/schemas/AlertRule'
      title: AlertRulesResp
      example:
        alert_rules:
        - has_resource_blacklist: true
          level: level
          resource_type: resource_type
          trigger_mode: trigger_mode
          trigger_value: trigger_value
          update: '2000-01-23T04:56:07.000+00:00'
          type: type
          enabled: true
          trigger_period: 6
          create: '2000-01-23T04:56:07.000+00:00'
          alarm_id: alarm_id
          id: 0
          group: group
        - has_resource_blacklist: true
          level: level
          resource_type: resource_type
          trigger_mode: trigger_mode
          trigger_value: trigger_value
          update: '2000-01-23T04:56:07.000+00:00'
          type: type
          enabled: true
          trigger_period: 6
          create: '2000-01-23T04:56:07.000+00:00'
          alarm_id: alarm_id
          id: 0
          group: group
    AlertRuleUpdateReq:
      type: object
      required:
      - alert_rule
      properties:
        alert_rule:
          $ref: '#/components/schemas/AlertRuleUpdateReq_Rule'
      title: AlertRuleUpdateReq
      example:
        alert_rule:
          trigger_period: 0
          trigger_value: trigger_value
          enabled: true
    AlertRuleSchema:
      type: object
      properties:
        events:
          type: array
          items:
            type: string
        types:
          type: array
          items:
            type: string
      title: AlertRuleSchema
      description: AlertRuleSchema defines alert rule schema
      example:
        types:
        - types
        - types
        events:
        - events
        - events
    AlertRuleCreateReq:
      type: object
      required:
      - alert_rule
      properties:
        alert_rule:
          $ref: '#/components/schemas/AlertRuleCreateReq_Rule'
      title: AlertRuleCreateReq
      example:
        alert_rule:
          level: level
          trigger_period: 0
          resource_type: resource_type
          trigger_mode: trigger_mode
          trigger_value: trigger_value
          type: type
          enabled: true
    UpdateAlertRuleResourceBlacklistReq_AlertRuleResourceBlacklist:
      type: object
      properties:
        resource_ids:
          type: array
          description: 'resource blacklist id must array, ex: [1, 2, 3]'
          items:
            type: integer
            format: int64
      title: UpdateAlertRuleResourceBlacklistReq_AlertRuleResourceBlacklist
      example:
        resource_ids:
        - 0
        - 0
    UpdateAlertRuleResourceBlacklistReq:
      type: object
      required:
      - alert_rule_resource_blacklist
      properties:
        alert_rule_resource_blacklist:
          description: create resource blacklist request
          $ref: '#/components/schemas/UpdateAlertRuleResourceBlacklistReq_AlertRuleResourceBlacklist'
      title: UpdateAlertRuleResourceBlacklistReq
      example:
        alert_rule_resource_blacklist:
          resource_ids:
          - 0
          - 0
    AlertRule:
      type: object
      properties:
        alarm_id:
          type: string
        create:
          type: string
          format: date-time
        enabled:
          type: boolean
        group:
          type: string
        has_resource_blacklist:
          type: boolean
        id:
          type: integer
          format: int64
        level:
          type: string
        resource_type:
          type: string
        trigger_mode:
          type: string
        trigger_period:
          type: integer
          format: int64
        trigger_value:
          type: string
        type:
          type: string
        update:
          type: string
          format: date-time
      title: AlertRule
      description: AlertRule defines the alert rule
      example:
        has_resource_blacklist: true
        level: level
        resource_type: resource_type
        trigger_mode: trigger_mode
        trigger_value: trigger_value
        update: '2000-01-23T04:56:07.000+00:00'
        type: type
        enabled: true
        trigger_period: 6
        create: '2000-01-23T04:56:07.000+00:00'
        alarm_id: alarm_id
        id: 0
        group: group
    AlertRuleCreateReq_Rule:
      type: object
      properties:
        enabled:
          type: boolean
        level:
          type: string
        resource_type:
          type: string
        trigger_mode:
          type: string
        trigger_period:
          type: integer
          format: int64
        trigger_value:
          type: string
        type:
          type: string
      title: AlertRuleCreateReq_Rule
      example:
        level: level
        trigger_period: 0
        resource_type: resource_type
        trigger_mode: trigger_mode
        trigger_value: trigger_value
        type: type
        enabled: true
    AlertRuleResp:
      type: object
      required:
      - alert_rule
      properties:
        alert_rule:
          description: alert rule
          $ref: '#/components/schemas/AlertRule'
      title: AlertRuleResp
      example:
        alert_rule:
          has_resource_blacklist: true
          level: level
          resource_type: resource_type
          trigger_mode: trigger_mode
          trigger_value: trigger_value
          update: '2000-01-23T04:56:07.000+00:00'
          type: type
          enabled: true
          trigger_period: 6
          create: '2000-01-23T04:56:07.000+00:00'
          alarm_id: alarm_id
          id: 0
          group: group
    AlertRuleSchemaResp:
      type: object
      required:
      - rule_schema_map
      - trigger_modes
      properties:
        rule_schema_map:
          type: object
          description: rule schemas
          additionalProperties:
            $ref: '#/components/schemas/AlertRuleSchema'
        trigger_modes:
          type: array
          description: trigger modes
          items:
            type: string
      title: AlertRuleSchemaResp
      example:
        trigger_modes:
        - trigger_modes
        - trigger_modes
        rule_schema_map:
          key:
            types:
            - types
            - types
            events:
            - events
            - events
    AlertRuleResourceBlacklistResp:
      type: object
      title: AlertRuleResourceBlacklistResp
  securitySchemes:
    tokenInHeader:
      description: auth by token
      type: apiKey
      name: Xms-Auth-Token
      in: header
    tokenInQuery:
      description: auth by token
      type: apiKey
      name: token
      in: query
